# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_KafkaTool.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_KafkaTool(object):
    def setupUi(self, KafkaTool):
        KafkaTool.setObjectName("KafkaTool")
        KafkaTool.resize(920, 628)
        self.gridLayout_4 = QtWidgets.QGridLayout(KafkaTool)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.textEdit = QtWidgets.QTextEdit(KafkaTool)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_4.addWidget(self.textEdit, 0, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(KafkaTool)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.IP = QtWidgets.QLineEdit(self.groupBox_2)
        self.IP.setMinimumSize(QtCore.QSize(140, 0))
        self.IP.setMaximumSize(QtCore.QSize(140, 16777215))
        self.IP.setObjectName("IP")
        self.horizontalLayout.addWidget(self.IP)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.pwd = QtWidgets.QLineEdit(self.groupBox_2)
        self.pwd.setMinimumSize(QtCore.QSize(140, 0))
        self.pwd.setMaximumSize(QtCore.QSize(140, 16777215))
        self.pwd.setObjectName("pwd")
        self.horizontalLayout_4.addWidget(self.pwd)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.usr = QtWidgets.QLineEdit(self.groupBox_2)
        self.usr.setMinimumSize(QtCore.QSize(140, 0))
        self.usr.setMaximumSize(QtCore.QSize(140, 16777215))
        self.usr.setObjectName("usr")
        self.horizontalLayout_3.addWidget(self.usr)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.port = QtWidgets.QLineEdit(self.groupBox_2)
        self.port.setMinimumSize(QtCore.QSize(140, 0))
        self.port.setMaximumSize(QtCore.QSize(140, 16777215))
        self.port.setObjectName("port")
        self.horizontalLayout_2.addWidget(self.port)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_close = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_close.setObjectName("pushButton_close")
        self.horizontalLayout_5.addWidget(self.pushButton_close)
        self.pushButton_con = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_con.setObjectName("pushButton_con")
        self.horizontalLayout_5.addWidget(self.pushButton_con)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 4, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(KafkaTool)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.comboBox)
        self.lineEdit_param = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_param.setObjectName("lineEdit_param")
        self.verticalLayout.addWidget(self.lineEdit_param)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.pushButton_search = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_search.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_search.setObjectName("pushButton_search")
        self.horizontalLayout_6.addWidget(self.pushButton_search)
        self.gridLayout.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.pushButton_do = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_do.setObjectName("pushButton_do")
        self.horizontalLayout_7.addWidget(self.pushButton_do)
        self.gridLayout.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        self.lineEdit_cmd = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_cmd.setObjectName("lineEdit_cmd")
        self.gridLayout.addWidget(self.lineEdit_cmd, 2, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 1, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 168, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem4, 2, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 1, 1, 1)
        self.gridLayout_4.setColumnStretch(0, 2)
        self.gridLayout_4.setColumnStretch(1, 1)
        self.textEdit.raise_()
        self.pushButton_con.raise_()
        self.pushButton_close.raise_()
        self.usr.raise_()
        self.pwd.raise_()
        self.port.raise_()
        self.IP.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.comboBox.raise_()
        self.pushButton_search.raise_()
        self.label_5.raise_()
        self.pushButton_do.raise_()
        self.groupBox.raise_()
        self.groupBox_2.raise_()

        self.retranslateUi(KafkaTool)
        QtCore.QMetaObject.connectSlotsByName(KafkaTool)

    def retranslateUi(self, KafkaTool):
        _translate = QtCore.QCoreApplication.translate
        KafkaTool.setWindowTitle(_translate("KafkaTool", "KafkaTool"))
        self.groupBox_2.setTitle(_translate("KafkaTool", "链接"))
        self.label.setText(_translate("KafkaTool", "服务器IP"))
        self.IP.setText(_translate("KafkaTool", "10.1.63.127"))
        self.label_4.setText(_translate("KafkaTool", "密码"))
        self.pwd.setText(_translate("KafkaTool", "aUmMZbhZ88Am31llaAgykfjYhArcjjWA"))
        self.label_3.setText(_translate("KafkaTool", "用户名"))
        self.usr.setText(_translate("KafkaTool", "welinkde"))
        self.label_2.setText(_translate("KafkaTool", "端口号"))
        self.port.setText(_translate("KafkaTool", "55519"))
        self.pushButton_close.setText(_translate("KafkaTool", "断开"))
        self.pushButton_con.setText(_translate("KafkaTool", "链接"))
        self.groupBox.setTitle(_translate("KafkaTool", "指令"))
        self.comboBox.setItemText(0, _translate("KafkaTool", "查看消费者组"))
        self.comboBox.setItemText(1, _translate("KafkaTool", "查看topic消费情况"))
        self.pushButton_search.setText(_translate("KafkaTool", "查询"))
        self.label_5.setText(_translate("KafkaTool", "自定义指令"))
        self.pushButton_do.setText(_translate("KafkaTool", "执行"))

