# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Monitor_Cloud.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Monitor_Cloud(object):
    def setupUi(self, Monitor_Cloud):
        Monitor_Cloud.setObjectName("Monitor_Cloud")
        Monitor_Cloud.resize(750, 514)
        self.gridLayout_4 = QtWidgets.QGridLayout(Monitor_Cloud)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox = QtWidgets.QCheckBox(Monitor_Cloud)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)
        self.groupBox = QtWidgets.QGroupBox(Monitor_Cloud)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.comboBox_RunTimeState = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_RunTimeState.setObjectName("comboBox_RunTimeState")
        self.comboBox_RunTimeState.addItem("")
        self.comboBox_RunTimeState.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox_RunTimeState)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.lineEdit_reportTotal = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_reportTotal.setObjectName("lineEdit_reportTotal")
        self.horizontalLayout_2.addWidget(self.lineEdit_reportTotal)
        self.gridLayout.addLayout(self.horizontalLayout_2, 8, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.lineEdit_reportTimeInterval = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_reportTimeInterval.setObjectName("lineEdit_reportTimeInterval")
        self.horizontalLayout_7.addWidget(self.lineEdit_reportTimeInterval)
        self.gridLayout.addLayout(self.horizontalLayout_7, 5, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.lineEdit_submitTotal = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_submitTotal.setObjectName("lineEdit_submitTotal")
        self.horizontalLayout_8.addWidget(self.lineEdit_submitTotal)
        self.gridLayout.addLayout(self.horizontalLayout_8, 6, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem4)
        self.dateTimeEdit_NotifyTime = QtWidgets.QDateTimeEdit(self.groupBox)
        self.dateTimeEdit_NotifyTime.setObjectName("dateTimeEdit_NotifyTime")
        self.horizontalLayout_9.addWidget(self.dateTimeEdit_NotifyTime)
        self.gridLayout.addLayout(self.horizontalLayout_9, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.lineEdit_QueueStock = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_QueueStock.setObjectName("lineEdit_QueueStock")
        self.horizontalLayout_5.addWidget(self.lineEdit_QueueStock)
        self.gridLayout.addLayout(self.horizontalLayout_5, 3, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.lineEdit_lastTimeQueueStock = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_lastTimeQueueStock.setObjectName("lineEdit_lastTimeQueueStock")
        self.horizontalLayout_6.addWidget(self.lineEdit_lastTimeQueueStock)
        self.gridLayout.addLayout(self.horizontalLayout_6, 4, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.lineEdit_submitFail = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_submitFail.setObjectName("lineEdit_submitFail")
        self.horizontalLayout_3.addWidget(self.lineEdit_submitFail)
        self.gridLayout.addLayout(self.horizontalLayout_3, 7, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem8)
        self.lineEdit_reportFail = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_reportFail.setObjectName("lineEdit_reportFail")
        self.horizontalLayout_10.addWidget(self.lineEdit_reportFail)
        self.gridLayout.addLayout(self.horizontalLayout_10, 9, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem9)
        self.lineEdit_ResourceId = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_ResourceId.setObjectName("lineEdit_ResourceId")
        self.horizontalLayout.addWidget(self.lineEdit_ResourceId)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.gridLayout_4.addLayout(self.verticalLayout, 0, 0, 2, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_2 = QtWidgets.QCheckBox(Monitor_Cloud)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_2.addWidget(self.checkBox_2)
        self.groupBox_2 = QtWidgets.QGroupBox(Monitor_Cloud)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_11.addWidget(self.label_11)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem10)
        self.lineEdit_dispatchCenterId = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_dispatchCenterId.setObjectName("lineEdit_dispatchCenterId")
        self.horizontalLayout_11.addWidget(self.lineEdit_dispatchCenterId)
        self.gridLayout_2.addLayout(self.horizontalLayout_11, 0, 0, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_13.addWidget(self.label_13)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem11)
        self.lineEdit_succDispatchCnt = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_succDispatchCnt.setObjectName("lineEdit_succDispatchCnt")
        self.horizontalLayout_13.addWidget(self.lineEdit_succDispatchCnt)
        self.gridLayout_2.addLayout(self.horizontalLayout_13, 2, 0, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_14.addWidget(self.label_14)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem12)
        self.lineEdit_failDispatchCnt = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_failDispatchCnt.setObjectName("lineEdit_failDispatchCnt")
        self.horizontalLayout_14.addWidget(self.lineEdit_failDispatchCnt)
        self.gridLayout_2.addLayout(self.horizontalLayout_14, 3, 0, 1, 1)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_15.addWidget(self.label_15)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem13)
        self.lineEdit_cycleTime = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_cycleTime.setObjectName("lineEdit_cycleTime")
        self.horizontalLayout_15.addWidget(self.lineEdit_cycleTime)
        self.gridLayout_2.addLayout(self.horizontalLayout_15, 4, 0, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_12.addWidget(self.label_12)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem14)
        self.lineEdit_totalDispatchCnt = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_totalDispatchCnt.setObjectName("lineEdit_totalDispatchCnt")
        self.horizontalLayout_12.addWidget(self.lineEdit_totalDispatchCnt)
        self.gridLayout_2.addLayout(self.horizontalLayout_12, 1, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.gridLayout_4.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkBox_3 = QtWidgets.QCheckBox(Monitor_Cloud)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout_3.addWidget(self.checkBox_3)
        self.groupBox_3 = QtWidgets.QGroupBox(Monitor_Cloud)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_17 = QtWidgets.QLabel(self.groupBox_3)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_17.addWidget(self.label_17)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem15)
        self.lineEdit_succCnt = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_succCnt.setObjectName("lineEdit_succCnt")
        self.horizontalLayout_17.addWidget(self.lineEdit_succCnt)
        self.gridLayout_3.addLayout(self.horizontalLayout_17, 1, 0, 1, 1)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_16 = QtWidgets.QLabel(self.groupBox_3)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_16.addWidget(self.label_16)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem16)
        self.lineEdit_resourceId = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_resourceId.setObjectName("lineEdit_resourceId")
        self.horizontalLayout_16.addWidget(self.lineEdit_resourceId)
        self.gridLayout_3.addLayout(self.horizontalLayout_16, 0, 0, 1, 1)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_18 = QtWidgets.QLabel(self.groupBox_3)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_18.addWidget(self.label_18)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem17)
        self.lineEdit_failCnt = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_failCnt.setObjectName("lineEdit_failCnt")
        self.horizontalLayout_18.addWidget(self.lineEdit_failCnt)
        self.gridLayout_3.addLayout(self.horizontalLayout_18, 2, 0, 1, 1)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_19 = QtWidgets.QLabel(self.groupBox_3)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_19.addWidget(self.label_19)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem18)
        self.lineEdit_cycleTime_2 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_cycleTime_2.setObjectName("lineEdit_cycleTime_2")
        self.horizontalLayout_19.addWidget(self.lineEdit_cycleTime_2)
        self.gridLayout_3.addLayout(self.horizontalLayout_19, 3, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.gridLayout_4.addLayout(self.verticalLayout_3, 1, 1, 1, 1)

        self.retranslateUi(Monitor_Cloud)
        QtCore.QMetaObject.connectSlotsByName(Monitor_Cloud)

    def retranslateUi(self, Monitor_Cloud):
        _translate = QtCore.QCoreApplication.translate
        Monitor_Cloud.setWindowTitle(_translate("Monitor_Cloud", "Form"))
        self.checkBox.setText(_translate("Monitor_Cloud", "ResourceStateNotify"))
        self.label_4.setText(_translate("Monitor_Cloud", "资源状态"))
        self.comboBox_RunTimeState.setItemText(0, _translate("Monitor_Cloud", "启用"))
        self.comboBox_RunTimeState.setItemText(1, _translate("Monitor_Cloud", "停用"))
        self.label_2.setText(_translate("Monitor_Cloud", "报告总数"))
        self.lineEdit_reportTotal.setText(_translate("Monitor_Cloud", "0"))
        self.label_7.setText(_translate("Monitor_Cloud", "报告频率"))
        self.lineEdit_reportTimeInterval.setText(_translate("Monitor_Cloud", "5"))
        self.label_8.setText(_translate("Monitor_Cloud", "提交总数"))
        self.lineEdit_submitTotal.setText(_translate("Monitor_Cloud", "0"))
        self.label_9.setText(_translate("Monitor_Cloud", "报告时间"))
        self.dateTimeEdit_NotifyTime.setDisplayFormat(_translate("Monitor_Cloud", "yyyy/M/d H:mm:ss"))
        self.label_5.setText(_translate("Monitor_Cloud", "队列积压数"))
        self.lineEdit_QueueStock.setText(_translate("Monitor_Cloud", "0"))
        self.label_6.setText(_translate("Monitor_Cloud", "最后时间积压数"))
        self.lineEdit_lastTimeQueueStock.setText(_translate("Monitor_Cloud", "0"))
        self.label_3.setText(_translate("Monitor_Cloud", "提交失败"))
        self.lineEdit_submitFail.setText(_translate("Monitor_Cloud", "0"))
        self.label_10.setText(_translate("Monitor_Cloud", "报告失败"))
        self.lineEdit_reportFail.setText(_translate("Monitor_Cloud", "0"))
        self.label.setText(_translate("Monitor_Cloud", "资源id"))
        self.lineEdit_ResourceId.setText(_translate("Monitor_Cloud", "0"))
        self.checkBox_2.setText(_translate("Monitor_Cloud", "SDispatchStatistics"))
        self.label_11.setText(_translate("Monitor_Cloud", "调度id"))
        self.lineEdit_dispatchCenterId.setText(_translate("Monitor_Cloud", "0"))
        self.label_13.setText(_translate("Monitor_Cloud", "调度成功"))
        self.lineEdit_succDispatchCnt.setText(_translate("Monitor_Cloud", "0"))
        self.label_14.setText(_translate("Monitor_Cloud", "调度失败"))
        self.lineEdit_failDispatchCnt.setText(_translate("Monitor_Cloud", "0"))
        self.label_15.setText(_translate("Monitor_Cloud", "循环次数"))
        self.lineEdit_cycleTime.setText(_translate("Monitor_Cloud", "0"))
        self.label_12.setText(_translate("Monitor_Cloud", "总调度数"))
        self.lineEdit_totalDispatchCnt.setText(_translate("Monitor_Cloud", "0"))
        self.checkBox_3.setText(_translate("Monitor_Cloud", "SResComStatistics"))
        self.label_17.setText(_translate("Monitor_Cloud", "成功数"))
        self.lineEdit_succCnt.setText(_translate("Monitor_Cloud", "0"))
        self.label_16.setText(_translate("Monitor_Cloud", "资源id"))
        self.lineEdit_resourceId.setText(_translate("Monitor_Cloud", "0"))
        self.label_18.setText(_translate("Monitor_Cloud", "失败数"))
        self.lineEdit_failCnt.setText(_translate("Monitor_Cloud", "0"))
        self.label_19.setText(_translate("Monitor_Cloud", "循环次数"))
        self.lineEdit_cycleTime_2.setText(_translate("Monitor_Cloud", "0"))

