# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_MoAccBlist.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MoAccBlist(object):
    def setupUi(self, MoAccBlist):
        MoAccBlist.setObjectName("MoAccBlist")
        MoAccBlist.resize(769, 300)
        self.gridLayout = QtWidgets.QGridLayout(MoAccBlist)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(MoAccBlist)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.lineEdit_accid = QtWidgets.QLineEdit(MoAccBlist)
        self.lineEdit_accid.setObjectName("lineEdit_accid")
        self.horizontalLayout_2.addWidget(self.lineEdit_accid)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(MoAccBlist)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.lineEdit_mobile = QtWidgets.QLineEdit(MoAccBlist)
        self.lineEdit_mobile.setObjectName("lineEdit_mobile")
        self.horizontalLayout.addWidget(self.lineEdit_mobile)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(MoAccBlist)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.lineEdit_level = QtWidgets.QLineEdit(MoAccBlist)
        self.lineEdit_level.setObjectName("lineEdit_level")
        self.horizontalLayout_3.addWidget(self.lineEdit_level)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(MoAccBlist)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.lineEdit_opertor = QtWidgets.QLineEdit(MoAccBlist)
        self.lineEdit_opertor.setObjectName("lineEdit_opertor")
        self.horizontalLayout_5.addWidget(self.lineEdit_opertor)
        self.gridLayout.addLayout(self.horizontalLayout_5, 4, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(MoAccBlist)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.lineEdit_remark = QtWidgets.QLineEdit(MoAccBlist)
        self.lineEdit_remark.setObjectName("lineEdit_remark")
        self.horizontalLayout_6.addWidget(self.lineEdit_remark)
        self.gridLayout.addLayout(self.horizontalLayout_6, 5, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(MoAccBlist)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.lineEdit_flag = QtWidgets.QLineEdit(MoAccBlist)
        self.lineEdit_flag.setObjectName("lineEdit_flag")
        self.horizontalLayout_4.addWidget(self.lineEdit_flag)
        self.gridLayout.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 2, 1, 1, 1)

        self.retranslateUi(MoAccBlist)
        QtCore.QMetaObject.connectSlotsByName(MoAccBlist)

    def retranslateUi(self, MoAccBlist):
        _translate = QtCore.QCoreApplication.translate
        MoAccBlist.setWindowTitle(_translate("MoAccBlist", "Form"))
        self.label_2.setText(_translate("MoAccBlist", "账户ID    "))
        self.lineEdit_accid.setText(_translate("MoAccBlist", "123"))
        self.label.setText(_translate("MoAccBlist", "电话号码  "))
        self.lineEdit_mobile.setText(_translate("MoAccBlist", "13000000000"))
        self.label_3.setText(_translate("MoAccBlist", "黑名单级别"))
        self.lineEdit_level.setText(_translate("MoAccBlist", "1"))
        self.label_5.setText(_translate("MoAccBlist", "Operator  "))
        self.lineEdit_opertor.setText(_translate("MoAccBlist", "system"))
        self.label_6.setText(_translate("MoAccBlist", "Remark    "))
        self.lineEdit_remark.setText(_translate("MoAccBlist", "mark"))
        self.label_4.setText(_translate("MoAccBlist", "Flag      "))
        self.lineEdit_flag.setText(_translate("MoAccBlist", "1"))

