# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_SHisRepData.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SHisRepData(object):
    def setupUi(self, SHisRepData):
        SHisRepData.setObjectName("SHisRepData")
        SHisRepData.resize(634, 359)
        self.gridLayout = QtWidgets.QGridLayout(SHisRepData)
        self.gridLayout.setContentsMargins(0, 0, 0, 7)
        self.gridLayout.setSpacing(7)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(SHisRepData)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lineEdit_mobile = QtWidgets.QLineEdit(SHisRepData)
        self.lineEdit_mobile.setObjectName("lineEdit_mobile")
        self.horizontalLayout.addWidget(self.lineEdit_mobile)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(SHisRepData)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.lineEdit_matchId = QtWidgets.QLineEdit(SHisRepData)
        self.lineEdit_matchId.setObjectName("lineEdit_matchId")
        self.horizontalLayout_2.addWidget(self.lineEdit_matchId)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(SHisRepData)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.lineEdit_resId = QtWidgets.QLineEdit(SHisRepData)
        self.lineEdit_resId.setObjectName("lineEdit_resId")
        self.horizontalLayout_3.addWidget(self.lineEdit_resId)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(SHisRepData)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(SHisRepData)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.horizontalLayout_4.addWidget(self.dateTimeEdit)
        self.gridLayout.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(SHisRepData)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.lineEdit_reportState = QtWidgets.QLineEdit(SHisRepData)
        self.lineEdit_reportState.setObjectName("lineEdit_reportState")
        self.horizontalLayout_5.addWidget(self.lineEdit_reportState)
        self.gridLayout.addLayout(self.horizontalLayout_5, 4, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(SHisRepData)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.lineEdit_flagBits = QtWidgets.QLineEdit(SHisRepData)
        self.lineEdit_flagBits.setObjectName("lineEdit_flagBits")
        self.horizontalLayout_6.addWidget(self.lineEdit_flagBits)
        self.gridLayout.addLayout(self.horizontalLayout_6, 5, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(SHisRepData)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.lineEdit_retryTimes = QtWidgets.QLineEdit(SHisRepData)
        self.lineEdit_retryTimes.setObjectName("lineEdit_retryTimes")
        self.horizontalLayout_7.addWidget(self.lineEdit_retryTimes)
        self.gridLayout.addLayout(self.horizontalLayout_7, 6, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_8 = QtWidgets.QLabel(SHisRepData)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.textEdit = QtWidgets.QTextEdit(SHisRepData)
        self.textEdit.setDocumentTitle("")
        self.textEdit.setPlaceholderText("")
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.gridLayout.addLayout(self.verticalLayout, 7, 0, 1, 1)

        self.retranslateUi(SHisRepData)
        QtCore.QMetaObject.connectSlotsByName(SHisRepData)

    def retranslateUi(self, SHisRepData):
        _translate = QtCore.QCoreApplication.translate
        SHisRepData.setWindowTitle(_translate("SHisRepData", "Form"))
        self.label.setText(_translate("SHisRepData", "手机号码      "))
        self.lineEdit_mobile.setText(_translate("SHisRepData", "13000000000"))
        self.label_2.setText(_translate("SHisRepData", "匹配编号      "))
        self.lineEdit_matchId.setText(_translate("SHisRepData", "0"))
        self.label_3.setText(_translate("SHisRepData", "资源ID        "))
        self.lineEdit_resId.setText(_translate("SHisRepData", "0"))
        self.label_4.setText(_translate("SHisRepData", "回执时间      "))
        self.label_5.setText(_translate("SHisRepData", "是否成功      "))
        self.lineEdit_reportState.setText(_translate("SHisRepData", "0"))
        self.label_6.setText(_translate("SHisRepData", "flagbits      "))
        self.lineEdit_flagBits.setText(_translate("SHisRepData", "0"))
        self.label_7.setText(_translate("SHisRepData", "重新匹配次数  "))
        self.lineEdit_retryTimes.setText(_translate("SHisRepData", "0"))
        self.label_8.setText(_translate("SHisRepData", "回执内容"))

