# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_SMOData.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SMOData(object):
    def setupUi(self, SMOData):
        SMOData.setObjectName("SMOData")
        SMOData.resize(659, 334)
        self.gridLayout = QtWidgets.QGridLayout(SMOData)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(SMOData)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lineEdit_msgId = QtWidgets.QLineEdit(SMOData)
        self.lineEdit_msgId.setObjectName("lineEdit_msgId")
        self.horizontalLayout.addWidget(self.lineEdit_msgId)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(SMOData)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.lineEdit_mobilePhone = QtWidgets.QLineEdit(SMOData)
        self.lineEdit_mobilePhone.setObjectName("lineEdit_mobilePhone")
        self.horizontalLayout_2.addWidget(self.lineEdit_mobilePhone)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(SMOData)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.dateTimeEdit_MOTime = QtWidgets.QDateTimeEdit(SMOData)
        self.dateTimeEdit_MOTime.setObjectName("dateTimeEdit_MOTime")
        self.horizontalLayout_7.addWidget(self.dateTimeEdit_MOTime)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(SMOData)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.lineEdit_SPNo = QtWidgets.QLineEdit(SMOData)
        self.lineEdit_SPNo.setObjectName("lineEdit_SPNo")
        self.horizontalLayout_3.addWidget(self.lineEdit_SPNo)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(SMOData)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.lineEdit_resourceId = QtWidgets.QLineEdit(SMOData)
        self.lineEdit_resourceId.setObjectName("lineEdit_resourceId")
        self.horizontalLayout_4.addWidget(self.lineEdit_resourceId)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(SMOData)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.lineEdit_MOContentLength = QtWidgets.QLineEdit(SMOData)
        self.lineEdit_MOContentLength.setObjectName("lineEdit_MOContentLength")
        self.horizontalLayout_5.addWidget(self.lineEdit_MOContentLength)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(SMOData)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.lineEdit_msgType = QtWidgets.QLineEdit(SMOData)
        self.lineEdit_msgType.setObjectName("lineEdit_msgType")
        self.horizontalLayout_6.addWidget(self.lineEdit_msgType)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(SMOData)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem7)
        self.lineEdit_accountId = QtWidgets.QLineEdit(SMOData)
        self.lineEdit_accountId.setObjectName("lineEdit_accountId")
        self.horizontalLayout_8.addWidget(self.lineEdit_accountId)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_9 = QtWidgets.QLabel(SMOData)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.textEdit_MOContent = QtWidgets.QTextEdit(SMOData)
        self.textEdit_MOContent.setObjectName("textEdit_MOContent")
        self.verticalLayout_2.addWidget(self.textEdit_MOContent)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 1)

        self.retranslateUi(SMOData)
        QtCore.QMetaObject.connectSlotsByName(SMOData)

    def retranslateUi(self, SMOData):
        _translate = QtCore.QCoreApplication.translate
        SMOData.setWindowTitle(_translate("SMOData", "Form"))
        self.label.setText(_translate("SMOData", "信息编号"))
        self.lineEdit_msgId.setText(_translate("SMOData", "0"))
        self.label_2.setText(_translate("SMOData", "手机号码"))
        self.lineEdit_mobilePhone.setText(_translate("SMOData", "13000000000"))
        self.label_7.setText(_translate("SMOData", "上行时间"))
        self.dateTimeEdit_MOTime.setDisplayFormat(_translate("SMOData", "yyyy/M/d H:mm:ss"))
        self.label_3.setText(_translate("SMOData", "企业扩展号"))
        self.lineEdit_SPNo.setText(_translate("SMOData", "1069"))
        self.label_4.setText(_translate("SMOData", "资源编号"))
        self.lineEdit_resourceId.setText(_translate("SMOData", "0"))
        self.label_5.setText(_translate("SMOData", "上行消息长度"))
        self.lineEdit_MOContentLength.setText(_translate("SMOData", "5"))
        self.label_6.setText(_translate("SMOData", "信息类型"))
        self.lineEdit_msgType.setText(_translate("SMOData", "0"))
        self.label_8.setText(_translate("SMOData", "账户id"))
        self.lineEdit_accountId.setText(_translate("SMOData", "anbaili"))
        self.label_9.setText(_translate("SMOData", "上行内容"))
        self.textEdit_MOContent.setHtml(_translate("SMOData", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">退订成功</p></body></html>"))

