# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_SHisSendData.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SHisSendData(object):
    def setupUi(self, SHisSendData):
        SHisSendData.setObjectName("SHisSendData")
        SHisSendData.resize(990, 732)
        self.gridLayout_2 = QtWidgets.QGridLayout(SHisSendData)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_22 = QtWidgets.QLabel(SHisSendData)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_22.addWidget(self.label_22)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem)
        self.lineEdit_sign = QtWidgets.QLineEdit(SHisSendData)
        self.lineEdit_sign.setObjectName("lineEdit_sign")
        self.horizontalLayout_22.addWidget(self.lineEdit_sign)
        self.verticalLayout_3.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_23 = QtWidgets.QLabel(SHisSendData)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_23.addWidget(self.label_23)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem1)
        self.lineEdit_spno = QtWidgets.QLineEdit(SHisSendData)
        self.lineEdit_spno.setObjectName("lineEdit_spno")
        self.horizontalLayout_23.addWidget(self.lineEdit_spno)
        self.verticalLayout_3.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_24 = QtWidgets.QLabel(SHisSendData)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_24.addWidget(self.label_24)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem2)
        self.lineEdit_extnum = QtWidgets.QLineEdit(SHisSendData)
        self.lineEdit_extnum.setObjectName("lineEdit_extnum")
        self.horizontalLayout_24.addWidget(self.lineEdit_extnum)
        self.verticalLayout_3.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_25 = QtWidgets.QLabel(SHisSendData)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_25.addWidget(self.label_25)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem3)
        self.lineEdit_accmsgid = QtWidgets.QLineEdit(SHisSendData)
        self.lineEdit_accmsgid.setObjectName("lineEdit_accmsgid")
        self.horizontalLayout_25.addWidget(self.lineEdit_accmsgid)
        self.verticalLayout_3.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_26 = QtWidgets.QLabel(SHisSendData)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_26.addWidget(self.label_26)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem4)
        self.lineEdit_sendresult = QtWidgets.QLineEdit(SHisSendData)
        self.lineEdit_sendresult.setObjectName("lineEdit_sendresult")
        self.horizontalLayout_26.addWidget(self.lineEdit_sendresult)
        self.verticalLayout_3.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_27 = QtWidgets.QLabel(SHisSendData)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_27.addWidget(self.label_27)
        self.lineEdit_title = QtWidgets.QLineEdit(SHisSendData)
        self.lineEdit_title.setObjectName("lineEdit_title")
        self.horizontalLayout_27.addWidget(self.lineEdit_title)
        self.verticalLayout_3.addLayout(self.horizontalLayout_27)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_28 = QtWidgets.QLabel(SHisSendData)
        self.label_28.setObjectName("label_28")
        self.gridLayout.addWidget(self.label_28, 0, 0, 1, 1)
        self.textEdit_content_one = QtWidgets.QTextEdit(SHisSendData)
        self.textEdit_content_one.setObjectName("textEdit_content_one")
        self.gridLayout.addWidget(self.textEdit_content_one, 1, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_29 = QtWidgets.QLabel(SHisSendData)
        self.label_29.setObjectName("label_29")
        self.verticalLayout.addWidget(self.label_29)
        self.textEdit_content = QtWidgets.QTextEdit(SHisSendData)
        self.textEdit_content.setObjectName("textEdit_content")
        self.verticalLayout.addWidget(self.textEdit_content)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 2, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(SHisSendData)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.lineEdit_msgId = QtWidgets.QLineEdit(SHisSendData)
        self.lineEdit_msgId.setObjectName("lineEdit_msgId")
        self.horizontalLayout.addWidget(self.lineEdit_msgId)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(SHisSendData)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.lineEdit_accId = QtWidgets.QLineEdit(SHisSendData)
        self.lineEdit_accId.setObjectName("lineEdit_accId")
        self.horizontalLayout_2.addWidget(self.lineEdit_accId)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(SHisSendData)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.lineEdit_prdExId = QtWidgets.QLineEdit(SHisSendData)
        self.lineEdit_prdExId.setObjectName("lineEdit_prdExId")
        self.horizontalLayout_3.addWidget(self.lineEdit_prdExId)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(SHisSendData)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.lineEdit_submitPrdExid = QtWidgets.QLineEdit(SHisSendData)
        self.lineEdit_submitPrdExid.setObjectName("lineEdit_submitPrdExid")
        self.horizontalLayout_4.addWidget(self.lineEdit_submitPrdExid)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(SHisSendData)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem9)
        self.lineEdit_resId = QtWidgets.QLineEdit(SHisSendData)
        self.lineEdit_resId.setObjectName("lineEdit_resId")
        self.horizontalLayout_6.addWidget(self.lineEdit_resId)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(SHisSendData)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem10)
        self.dateTimeEdit_sendDateTime = QtWidgets.QDateTimeEdit(SHisSendData)
        self.dateTimeEdit_sendDateTime.setObjectName("dateTimeEdit_sendDateTime")
        self.horizontalLayout_5.addWidget(self.dateTimeEdit_sendDateTime)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(SHisSendData)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem11)
        self.dateTimeEdit_commitDateTime = QtWidgets.QDateTimeEdit(SHisSendData)
        self.dateTimeEdit_commitDateTime.setObjectName("dateTimeEdit_commitDateTime")
        self.horizontalLayout_7.addWidget(self.dateTimeEdit_commitDateTime)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(SHisSendData)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem12)
        self.lineEdit_mobile = QtWidgets.QLineEdit(SHisSendData)
        self.lineEdit_mobile.setObjectName("lineEdit_mobile")
        self.horizontalLayout_8.addWidget(self.lineEdit_mobile)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(SHisSendData)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem13)
        self.lineEdit_matchId = QtWidgets.QLineEdit(SHisSendData)
        self.lineEdit_matchId.setObjectName("lineEdit_matchId")
        self.horizontalLayout_9.addWidget(self.lineEdit_matchId)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(SHisSendData)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem14)
        self.lineEdit_pkTotal = QtWidgets.QLineEdit(SHisSendData)
        self.lineEdit_pkTotal.setObjectName("lineEdit_pkTotal")
        self.horizontalLayout_10.addWidget(self.lineEdit_pkTotal)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_11 = QtWidgets.QLabel(SHisSendData)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_11.addWidget(self.label_11)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem15)
        self.lineEdit_pkNum = QtWidgets.QLineEdit(SHisSendData)
        self.lineEdit_pkNum.setObjectName("lineEdit_pkNum")
        self.horizontalLayout_11.addWidget(self.lineEdit_pkNum)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_12 = QtWidgets.QLabel(SHisSendData)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_12.addWidget(self.label_12)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem16)
        self.lineEdit_chargeQuantity = QtWidgets.QLineEdit(SHisSendData)
        self.lineEdit_chargeQuantity.setObjectName("lineEdit_chargeQuantity")
        self.horizontalLayout_12.addWidget(self.lineEdit_chargeQuantity)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_13 = QtWidgets.QLabel(SHisSendData)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_13.addWidget(self.label_13)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem17)
        self.lineEdit_sendTimes = QtWidgets.QLineEdit(SHisSendData)
        self.lineEdit_sendTimes.setObjectName("lineEdit_sendTimes")
        self.horizontalLayout_13.addWidget(self.lineEdit_sendTimes)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_14 = QtWidgets.QLabel(SHisSendData)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_14.addWidget(self.label_14)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem18)
        self.lineEdit_msgType = QtWidgets.QLineEdit(SHisSendData)
        self.lineEdit_msgType.setObjectName("lineEdit_msgType")
        self.horizontalLayout_14.addWidget(self.lineEdit_msgType)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_15 = QtWidgets.QLabel(SHisSendData)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_15.addWidget(self.label_15)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem19)
        self.lineEdit_sendState = QtWidgets.QLineEdit(SHisSendData)
        self.lineEdit_sendState.setObjectName("lineEdit_sendState")
        self.horizontalLayout_15.addWidget(self.lineEdit_sendState)
        self.verticalLayout_2.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_16 = QtWidgets.QLabel(SHisSendData)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_16.addWidget(self.label_16)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem20)
        self.lineEdit_priority = QtWidgets.QLineEdit(SHisSendData)
        self.lineEdit_priority.setInputMask("")
        self.lineEdit_priority.setObjectName("lineEdit_priority")
        self.horizontalLayout_16.addWidget(self.lineEdit_priority)
        self.verticalLayout_2.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_17 = QtWidgets.QLabel(SHisSendData)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_17.addWidget(self.label_17)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem21)
        self.lineEdit_flagBits = QtWidgets.QLineEdit(SHisSendData)
        self.lineEdit_flagBits.setInputMask("")
        self.lineEdit_flagBits.setObjectName("lineEdit_flagBits")
        self.horizontalLayout_17.addWidget(self.lineEdit_flagBits)
        self.verticalLayout_2.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_18 = QtWidgets.QLabel(SHisSendData)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_18.addWidget(self.label_18)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem22)
        self.lineEdit_rmSndFldRsndTimes = QtWidgets.QLineEdit(SHisSendData)
        self.lineEdit_rmSndFldRsndTimes.setInputMask("")
        self.lineEdit_rmSndFldRsndTimes.setObjectName("lineEdit_rmSndFldRsndTimes")
        self.horizontalLayout_18.addWidget(self.lineEdit_rmSndFldRsndTimes)
        self.verticalLayout_2.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_19 = QtWidgets.QLabel(SHisSendData)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_19.addWidget(self.label_19)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem23)
        self.lineEdit_rmRepFldRsndTimes = QtWidgets.QLineEdit(SHisSendData)
        self.lineEdit_rmRepFldRsndTimes.setInputMask("")
        self.lineEdit_rmRepFldRsndTimes.setObjectName("lineEdit_rmRepFldRsndTimes")
        self.horizontalLayout_19.addWidget(self.lineEdit_rmRepFldRsndTimes)
        self.verticalLayout_2.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_20 = QtWidgets.QLabel(SHisSendData)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_20.addWidget(self.label_20)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem24)
        self.lineEdit_dealTimes = QtWidgets.QLineEdit(SHisSendData)
        self.lineEdit_dealTimes.setInputMask("")
        self.lineEdit_dealTimes.setObjectName("lineEdit_dealTimes")
        self.horizontalLayout_20.addWidget(self.lineEdit_dealTimes)
        self.verticalLayout_2.addLayout(self.horizontalLayout_20)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(SHisSendData)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 0, 1, 1, 1)

        self.retranslateUi(SHisSendData)
        QtCore.QMetaObject.connectSlotsByName(SHisSendData)

    def retranslateUi(self, SHisSendData):
        _translate = QtCore.QCoreApplication.translate
        SHisSendData.setWindowTitle(_translate("SHisSendData", "Form"))
        self.label_22.setText(_translate("SHisSendData", "签名        "))
        self.lineEdit_sign.setText(_translate("SHisSendData", "【微网通联】"))
        self.label_23.setText(_translate("SHisSendData", "服务商号    "))
        self.lineEdit_spno.setText(_translate("SHisSendData", "1065"))
        self.label_24.setText(_translate("SHisSendData", "扩展号码    "))
        self.lineEdit_extnum.setText(_translate("SHisSendData", "888"))
        self.label_25.setText(_translate("SHisSendData", "客户自定义id"))
        self.lineEdit_accmsgid.setText(_translate("SHisSendData", "999"))
        self.label_26.setText(_translate("SHisSendData", "发送结果内容"))
        self.label_27.setText(_translate("SHisSendData", "标题        "))
        self.label_28.setText(_translate("SHisSendData", "信息内容"))
        self.label_29.setText(_translate("SHisSendData", "整信息内容"))
        self.label.setText(_translate("SHisSendData", "消息编号  "))
        self.lineEdit_msgId.setText(_translate("SHisSendData", "0"))
        self.label_2.setText(_translate("SHisSendData", "账号ID    "))
        self.lineEdit_accId.setText(_translate("SHisSendData", "0"))
        self.label_3.setText(_translate("SHisSendData", "扩展产品ID"))
        self.lineEdit_prdExId.setText(_translate("SHisSendData", "0"))
        self.label_4.setText(_translate("SHisSendData", "提交产品ID"))
        self.lineEdit_submitPrdExid.setText(_translate("SHisSendData", "0"))
        self.label_6.setText(_translate("SHisSendData", "资源编号  "))
        self.lineEdit_resId.setText(_translate("SHisSendData", "0"))
        self.label_5.setText(_translate("SHisSendData", "发送时间  "))
        self.dateTimeEdit_sendDateTime.setDisplayFormat(_translate("SHisSendData", "yyyy/M/d H:mm:ss"))
        self.label_7.setText(_translate("SHisSendData", "提交时间  "))
        self.dateTimeEdit_commitDateTime.setDisplayFormat(_translate("SHisSendData", "yyyy/M/d H:mm:ss"))
        self.label_8.setText(_translate("SHisSendData", "手机号码  "))
        self.lineEdit_mobile.setText(_translate("SHisSendData", "13000000000"))
        self.label_9.setText(_translate("SHisSendData", "匹配编号  "))
        self.lineEdit_matchId.setText(_translate("SHisSendData", "0"))
        self.label_10.setText(_translate("SHisSendData", "信息总页数"))
        self.lineEdit_pkTotal.setText(_translate("SHisSendData", "0"))
        self.label_11.setText(_translate("SHisSendData", "当前页码  "))
        self.lineEdit_pkNum.setText(_translate("SHisSendData", "0"))
        self.label_12.setText(_translate("SHisSendData", "计费数    "))
        self.lineEdit_chargeQuantity.setText(_translate("SHisSendData", "0"))
        self.label_13.setText(_translate("SHisSendData", "发送次数  "))
        self.lineEdit_sendTimes.setText(_translate("SHisSendData", "0"))
        self.label_14.setText(_translate("SHisSendData", "消息类型  "))
        self.lineEdit_msgType.setText(_translate("SHisSendData", "0"))
        self.label_15.setText(_translate("SHisSendData", "发送状态  "))
        self.lineEdit_sendState.setText(_translate("SHisSendData", "0"))
        self.label_16.setText(_translate("SHisSendData", "消息级别  "))
        self.lineEdit_priority.setText(_translate("SHisSendData", "0"))
        self.label_17.setText(_translate("SHisSendData", "FlagBits "))
        self.lineEdit_flagBits.setText(_translate("SHisSendData", "0"))
        self.label_18.setText(_translate("SHisSendData", "发送失败剩余重发次数"))
        self.lineEdit_rmSndFldRsndTimes.setText(_translate("SHisSendData", "0"))
        self.label_19.setText(_translate("SHisSendData", "剩余回执问题重发次数"))
        self.lineEdit_rmRepFldRsndTimes.setText(_translate("SHisSendData", "0"))
        self.label_20.setText(_translate("SHisSendData", "处理次数  "))
        self.lineEdit_dealTimes.setText(_translate("SHisSendData", "0"))

