# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_SQL.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(700, 595)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.host = QtWidgets.QLineEdit(Form)
        self.host.setObjectName("host")
        self.horizontalLayout.addWidget(self.host)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.usr = QtWidgets.QLineEdit(Form)
        self.usr.setObjectName("usr")
        self.horizontalLayout_2.addWidget(self.usr)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.pwd = QtWidgets.QLineEdit(Form)
        self.pwd.setObjectName("pwd")
        self.horizontalLayout_3.addWidget(self.pwd)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 2, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.db = QtWidgets.QLineEdit(Form)
        self.db.setObjectName("db")
        self.horizontalLayout_4.addWidget(self.db)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 3, 1, 1)
        self.connect = QtWidgets.QPushButton(Form)
        self.connect.setObjectName("connect")
        self.gridLayout.addWidget(self.connect, 0, 4, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.T_ModulesRelationship = QtWidgets.QTreeWidget(self.widget)
        self.T_ModulesRelationship.setStyleSheet("")
        self.T_ModulesRelationship.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.T_ModulesRelationship.setTabKeyNavigation(False)
        self.T_ModulesRelationship.setProperty("showDropIndicator", True)
        self.T_ModulesRelationship.setDragEnabled(True)
        self.T_ModulesRelationship.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.T_ModulesRelationship.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.T_ModulesRelationship.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.T_ModulesRelationship.setAnimated(True)
        self.T_ModulesRelationship.setAllColumnsShowFocus(True)
        self.T_ModulesRelationship.setWordWrap(False)
        self.T_ModulesRelationship.setObjectName("T_ModulesRelationship")
        self.T_ModulesRelationship.header().setDefaultSectionSize(250)
        self.T_ModulesRelationship.header().setMinimumSectionSize(125)
        self.gridLayout_2.addWidget(self.T_ModulesRelationship, 0, 0, 1, 1)
        self.tabWidget.addTab(self.widget, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 5)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "host"))
        self.host.setText(_translate("Form", "10.1.120.87"))
        self.label_2.setText(_translate("Form", "usr"))
        self.usr.setText(_translate("Form", "sa"))
        self.label_3.setText(_translate("Form", "pwd"))
        self.pwd.setText(_translate("Form", "admin123!@#"))
        self.label_4.setText(_translate("Form", "db"))
        self.db.setText(_translate("Form", "DevelopData"))
        self.connect.setText(_translate("Form", "链接"))
        self.T_ModulesRelationship.setSortingEnabled(True)
        self.T_ModulesRelationship.headerItem().setText(0, _translate("Form", "模块"))
        self.T_ModulesRelationship.headerItem().setText(1, _translate("Form", "依赖模块"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), _translate("Form", "T_ModulesRelationship"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Tab 2"))

