# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_SQL.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SQL(object):
    def setupUi(self, SQL):
        SQL.setObjectName("SQL")
        SQL.setWindowModality(QtCore.Qt.NonModal)
        SQL.resize(758, 509)
        self.gridLayout = QtWidgets.QGridLayout(SQL)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(SQL)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.host = QtWidgets.QLineEdit(SQL)
        self.host.setObjectName("host")
        self.horizontalLayout.addWidget(self.host)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(SQL)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.usr = QtWidgets.QLineEdit(SQL)
        self.usr.setObjectName("usr")
        self.horizontalLayout_2.addWidget(self.usr)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(SQL)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.pwd = QtWidgets.QLineEdit(SQL)
        self.pwd.setObjectName("pwd")
        self.horizontalLayout_3.addWidget(self.pwd)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 2, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(SQL)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.db = QtWidgets.QLineEdit(SQL)
        self.db.setObjectName("db")
        self.horizontalLayout_4.addWidget(self.db)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 3, 1, 1)
        self.connect = QtWidgets.QPushButton(SQL)
        self.connect.setObjectName("connect")
        self.gridLayout.addWidget(self.connect, 0, 4, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(SQL)
        self.tabWidget.setObjectName("tabWidget")
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.T_ModulesRelationship = QtWidgets.QTreeWidget(self.widget)
        self.T_ModulesRelationship.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.T_ModulesRelationship.setStyleSheet("")
        self.T_ModulesRelationship.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.T_ModulesRelationship.setTabKeyNavigation(False)
        self.T_ModulesRelationship.setProperty("showDropIndicator", True)
        self.T_ModulesRelationship.setDragEnabled(True)
        self.T_ModulesRelationship.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.T_ModulesRelationship.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.T_ModulesRelationship.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.T_ModulesRelationship.setAnimated(True)
        self.T_ModulesRelationship.setAllColumnsShowFocus(True)
        self.T_ModulesRelationship.setWordWrap(False)
        self.T_ModulesRelationship.setObjectName("T_ModulesRelationship")
        self.T_ModulesRelationship.header().setDefaultSectionSize(250)
        self.T_ModulesRelationship.header().setMinimumSectionSize(125)
        self.gridLayout_2.addWidget(self.T_ModulesRelationship, 0, 0, 1, 1)
        self.tabWidget.addTab(self.widget, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 5)
        self.action_add = QtWidgets.QAction(SQL)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_add.setIcon(icon)
        self.action_add.setObjectName("action_add")
        self.action_del = QtWidgets.QAction(SQL)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/image/edit_remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_del.setIcon(icon1)
        self.action_del.setObjectName("action_del")

        self.retranslateUi(SQL)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SQL)

    def retranslateUi(self, SQL):
        _translate = QtCore.QCoreApplication.translate
        SQL.setWindowTitle(_translate("SQL", "Dialog"))
        self.label.setText(_translate("SQL", "host"))
        self.host.setText(_translate("SQL", "10.1.120.87"))
        self.label_2.setText(_translate("SQL", "usr"))
        self.usr.setText(_translate("SQL", "sa"))
        self.label_3.setText(_translate("SQL", "pwd"))
        self.pwd.setText(_translate("SQL", "admin123!@#"))
        self.label_4.setText(_translate("SQL", "db"))
        self.db.setText(_translate("SQL", "DevelopData"))
        self.connect.setText(_translate("SQL", "链接"))
        self.T_ModulesRelationship.setSortingEnabled(True)
        self.T_ModulesRelationship.headerItem().setText(0, _translate("SQL", "模块"))
        self.T_ModulesRelationship.headerItem().setText(1, _translate("SQL", "依赖模块"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), _translate("SQL", "T_ModulesRelationship"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("SQL", "Tab 2"))
        self.action_add.setText(_translate("SQL", "添加"))
        self.action_del.setText(_translate("SQL", "删除"))
        self.action_del.setShortcut(_translate("SQL", "Del"))

import main_rc
