# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_SCloudMsg.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CloudMsg(object):
    def setupUi(self, CloudMsg):
        CloudMsg.setObjectName("CloudMsg")
        CloudMsg.resize(1018, 861)
        self.gridLayout = QtWidgets.QGridLayout(CloudMsg)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(CloudMsg)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.Priority = QtWidgets.QLineEdit(CloudMsg)
        self.Priority.setObjectName("Priority")
        self.horizontalLayout.addWidget(self.Priority)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(CloudMsg)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.MsgId = QtWidgets.QLineEdit(CloudMsg)
        self.MsgId.setObjectName("MsgId")
        self.horizontalLayout_2.addWidget(self.MsgId)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(CloudMsg)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.ProductExtendId = QtWidgets.QLineEdit(CloudMsg)
        self.ProductExtendId.setObjectName("ProductExtendId")
        self.horizontalLayout_3.addWidget(self.ProductExtendId)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(CloudMsg)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.RealProductExtendId = QtWidgets.QLineEdit(CloudMsg)
        self.RealProductExtendId.setObjectName("RealProductExtendId")
        self.horizontalLayout_4.addWidget(self.RealProductExtendId)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_24 = QtWidgets.QLabel(CloudMsg)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_24.addWidget(self.label_24)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem4)
        self.StartSendDateTime = QtWidgets.QDateTimeEdit(CloudMsg)
        self.StartSendDateTime.setObjectName("StartSendDateTime")
        self.horizontalLayout_24.addWidget(self.StartSendDateTime)
        self.verticalLayout.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_21 = QtWidgets.QLabel(CloudMsg)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_21.addWidget(self.label_21)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem5)
        self.EndSendDateTime = QtWidgets.QDateTimeEdit(CloudMsg)
        self.EndSendDateTime.setObjectName("EndSendDateTime")
        self.horizontalLayout_21.addWidget(self.EndSendDateTime)
        self.verticalLayout.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_22 = QtWidgets.QLabel(CloudMsg)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_22.addWidget(self.label_22)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem6)
        self.StartSendTime = QtWidgets.QDateTimeEdit(CloudMsg)
        self.StartSendTime.setObjectName("StartSendTime")
        self.horizontalLayout_22.addWidget(self.StartSendTime)
        self.verticalLayout.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_23 = QtWidgets.QLabel(CloudMsg)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_23.addWidget(self.label_23)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem7)
        self.EndSendTime = QtWidgets.QDateTimeEdit(CloudMsg)
        self.EndSendTime.setObjectName("EndSendTime")
        self.horizontalLayout_23.addWidget(self.EndSendTime)
        self.verticalLayout.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(CloudMsg)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem8)
        self.ChargeQuantity = QtWidgets.QLineEdit(CloudMsg)
        self.ChargeQuantity.setObjectName("ChargeQuantity")
        self.horizontalLayout_9.addWidget(self.ChargeQuantity)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(CloudMsg)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem9)
        self.MsgState = QtWidgets.QComboBox(CloudMsg)
        self.MsgState.setObjectName("MsgState")
        self.MsgState.addItem("")
        self.MsgState.addItem("")
        self.MsgState.addItem("")
        self.MsgState.addItem("")
        self.MsgState.addItem("")
        self.MsgState.addItem("")
        self.MsgState.addItem("")
        self.horizontalLayout_10.addWidget(self.MsgState)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_11 = QtWidgets.QLabel(CloudMsg)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_11.addWidget(self.label_11)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem10)
        self.MsgType = QtWidgets.QComboBox(CloudMsg)
        self.MsgType.setObjectName("MsgType")
        self.MsgType.addItem("")
        self.MsgType.addItem("")
        self.horizontalLayout_11.addWidget(self.MsgType)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_25 = QtWidgets.QLabel(CloudMsg)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_25.addWidget(self.label_25)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem11)
        self.CommitTime = QtWidgets.QDateTimeEdit(CloudMsg)
        self.CommitTime.setObjectName("CommitTime")
        self.horizontalLayout_25.addWidget(self.CommitTime)
        self.verticalLayout.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_13 = QtWidgets.QLabel(CloudMsg)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_13.addWidget(self.label_13)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem12)
        self.Package = QtWidgets.QLineEdit(CloudMsg)
        self.Package.setObjectName("Package")
        self.horizontalLayout_13.addWidget(self.Package)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_14 = QtWidgets.QLabel(CloudMsg)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_14.addWidget(self.label_14)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem13)
        self.MobilesContentLen = QtWidgets.QLineEdit(CloudMsg)
        self.MobilesContentLen.setObjectName("MobilesContentLen")
        self.horizontalLayout_14.addWidget(self.MobilesContentLen)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_15 = QtWidgets.QLabel(CloudMsg)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_15.addWidget(self.label_15)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem14)
        self.MsgContentLen = QtWidgets.QLineEdit(CloudMsg)
        self.MsgContentLen.setObjectName("MsgContentLen")
        self.horizontalLayout_15.addWidget(self.MsgContentLen)
        self.verticalLayout.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_16 = QtWidgets.QLabel(CloudMsg)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_16.addWidget(self.label_16)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem15)
        self.MobilesCount = QtWidgets.QLineEdit(CloudMsg)
        self.MobilesCount.setObjectName("MobilesCount")
        self.horizontalLayout_16.addWidget(self.MobilesCount)
        self.verticalLayout.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_17 = QtWidgets.QLabel(CloudMsg)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_17.addWidget(self.label_17)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem16)
        self.DispatchTimes = QtWidgets.QLineEdit(CloudMsg)
        self.DispatchTimes.setObjectName("DispatchTimes")
        self.horizontalLayout_17.addWidget(self.DispatchTimes)
        self.verticalLayout.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_18 = QtWidgets.QLabel(CloudMsg)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_18.addWidget(self.label_18)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem17)
        self.Telcom = QtWidgets.QComboBox(CloudMsg)
        self.Telcom.setObjectName("Telcom")
        self.Telcom.addItem("")
        self.Telcom.addItem("")
        self.Telcom.addItem("")
        self.Telcom.addItem("")
        self.horizontalLayout_18.addWidget(self.Telcom)
        self.verticalLayout.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_19 = QtWidgets.QLabel(CloudMsg)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_19.addWidget(self.label_19)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem18)
        self.ProvinceId = QtWidgets.QLineEdit(CloudMsg)
        self.ProvinceId.setObjectName("ProvinceId")
        self.horizontalLayout_19.addWidget(self.ProvinceId)
        self.verticalLayout.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(CloudMsg)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem19)
        self.CityId = QtWidgets.QLineEdit(CloudMsg)
        self.CityId.setObjectName("CityId")
        self.horizontalLayout_8.addWidget(self.CityId)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(CloudMsg)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem20)
        self.TPCBChecked = QtWidgets.QLineEdit(CloudMsg)
        self.TPCBChecked.setObjectName("TPCBChecked")
        self.horizontalLayout_7.addWidget(self.TPCBChecked)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(CloudMsg)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem21)
        self.SendedTimes = QtWidgets.QLineEdit(CloudMsg)
        self.SendedTimes.setObjectName("SendedTimes")
        self.horizontalLayout_6.addWidget(self.SendedTimes)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_12 = QtWidgets.QLabel(CloudMsg)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_12.addWidget(self.label_12)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem22)
        self.DispatchFailedState = QtWidgets.QLineEdit(CloudMsg)
        self.DispatchFailedState.setObjectName("DispatchFailedState")
        self.horizontalLayout_12.addWidget(self.DispatchFailedState)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(CloudMsg)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem23)
        self.SubmitType = QtWidgets.QLineEdit(CloudMsg)
        self.SubmitType.setObjectName("SubmitType")
        self.horizontalLayout_5.addWidget(self.SubmitType)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_20 = QtWidgets.QLabel(CloudMsg)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_20.addWidget(self.label_20)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem24)
        self.CloudMsgTemplateID = QtWidgets.QLineEdit(CloudMsg)
        self.CloudMsgTemplateID.setObjectName("CloudMsgTemplateID")
        self.horizontalLayout_20.addWidget(self.CloudMsgTemplateID)
        self.verticalLayout.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.label_50 = QtWidgets.QLabel(CloudMsg)
        self.label_50.setObjectName("label_50")
        self.horizontalLayout_46.addWidget(self.label_50)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_46.addItem(spacerItem25)
        self.CommitIp = QtWidgets.QLineEdit(CloudMsg)
        self.CommitIp.setObjectName("CommitIp")
        self.horizontalLayout_46.addWidget(self.CommitIp)
        self.verticalLayout.addLayout(self.horizontalLayout_46)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_26 = QtWidgets.QLabel(CloudMsg)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_26.addWidget(self.label_26)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem26)
        self.m_old_struct = QtWidgets.QLineEdit(CloudMsg)
        self.m_old_struct.setObjectName("m_old_struct")
        self.horizontalLayout_26.addWidget(self.m_old_struct)
        self.verticalLayout.addLayout(self.horizontalLayout_26)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 2, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_27 = QtWidgets.QLabel(CloudMsg)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_27.addWidget(self.label_27)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem27)
        self.pagetotal = QtWidgets.QLineEdit(CloudMsg)
        self.pagetotal.setObjectName("pagetotal")
        self.horizontalLayout_27.addWidget(self.pagetotal)
        self.verticalLayout_7.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_28 = QtWidgets.QLabel(CloudMsg)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_28.addWidget(self.label_28)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem28)
        self.packagetotal = QtWidgets.QLineEdit(CloudMsg)
        self.packagetotal.setObjectName("packagetotal")
        self.horizontalLayout_28.addWidget(self.packagetotal)
        self.verticalLayout_7.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_29 = QtWidgets.QLabel(CloudMsg)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_29.addWidget(self.label_29)
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem29)
        self.typeComponentParam = QtWidgets.QLineEdit(CloudMsg)
        self.typeComponentParam.setObjectName("typeComponentParam")
        self.horizontalLayout_29.addWidget(self.typeComponentParam)
        self.verticalLayout_7.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_30 = QtWidgets.QLabel(CloudMsg)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_30.addWidget(self.label_30)
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem30)
        self.lastFailResourceId = QtWidgets.QLineEdit(CloudMsg)
        self.lastFailResourceId.setObjectName("lastFailResourceId")
        self.horizontalLayout_30.addWidget(self.lastFailResourceId)
        self.verticalLayout_7.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_31 = QtWidgets.QLabel(CloudMsg)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_31.addWidget(self.label_31)
        spacerItem31 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem31)
        self.failedType = QtWidgets.QComboBox(CloudMsg)
        self.failedType.setObjectName("failedType")
        self.failedType.addItem("")
        self.failedType.addItem("")
        self.failedType.addItem("")
        self.failedType.addItem("")
        self.failedType.addItem("")
        self.failedType.addItem("")
        self.failedType.addItem("")
        self.failedType.addItem("")
        self.failedType.addItem("")
        self.horizontalLayout_31.addWidget(self.failedType)
        self.verticalLayout_7.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.label_37 = QtWidgets.QLabel(CloudMsg)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_37.addWidget(self.label_37)
        spacerItem32 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_37.addItem(spacerItem32)
        self.lastDiapatchTime = QtWidgets.QDateTimeEdit(CloudMsg)
        self.lastDiapatchTime.setObjectName("lastDiapatchTime")
        self.horizontalLayout_37.addWidget(self.lastDiapatchTime)
        self.verticalLayout_7.addLayout(self.horizontalLayout_37)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.label_33 = QtWidgets.QLabel(CloudMsg)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_33.addWidget(self.label_33)
        spacerItem33 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_33.addItem(spacerItem33)
        self.resourceSendTimes = QtWidgets.QLineEdit(CloudMsg)
        self.resourceSendTimes.setObjectName("resourceSendTimes")
        self.horizontalLayout_33.addWidget(self.resourceSendTimes)
        self.verticalLayout_7.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.label_34 = QtWidgets.QLabel(CloudMsg)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_34.addWidget(self.label_34)
        spacerItem34 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem34)
        self.auditorId = QtWidgets.QLineEdit(CloudMsg)
        self.auditorId.setObjectName("auditorId")
        self.horizontalLayout_34.addWidget(self.auditorId)
        self.verticalLayout_7.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.label_35 = QtWidgets.QLabel(CloudMsg)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_35.addWidget(self.label_35)
        spacerItem35 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem35)
        self.totalSendTimes = QtWidgets.QLineEdit(CloudMsg)
        self.totalSendTimes.setObjectName("totalSendTimes")
        self.horizontalLayout_35.addWidget(self.totalSendTimes)
        self.verticalLayout_7.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.label_36 = QtWidgets.QLabel(CloudMsg)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_36.addWidget(self.label_36)
        spacerItem36 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_36.addItem(spacerItem36)
        self.repResendTimeOut = QtWidgets.QLineEdit(CloudMsg)
        self.repResendTimeOut.setObjectName("repResendTimeOut")
        self.horizontalLayout_36.addWidget(self.repResendTimeOut)
        self.verticalLayout_7.addLayout(self.horizontalLayout_36)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.label_32 = QtWidgets.QLabel(CloudMsg)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_32.addWidget(self.label_32)
        spacerItem37 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem37)
        self.innerDispatchTimes = QtWidgets.QLineEdit(CloudMsg)
        self.innerDispatchTimes.setObjectName("innerDispatchTimes")
        self.horizontalLayout_32.addWidget(self.innerDispatchTimes)
        self.verticalLayout_7.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_47 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_47.setObjectName("horizontalLayout_47")
        self.label_51 = QtWidgets.QLabel(CloudMsg)
        self.label_51.setObjectName("label_51")
        self.horizontalLayout_47.addWidget(self.label_51)
        spacerItem38 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_47.addItem(spacerItem38)
        self.extComponentParam = QtWidgets.QLineEdit(CloudMsg)
        self.extComponentParam.setObjectName("extComponentParam")
        self.horizontalLayout_47.addWidget(self.extComponentParam)
        self.verticalLayout_7.addLayout(self.horizontalLayout_47)
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.label_38 = QtWidgets.QLabel(CloudMsg)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_38.addWidget(self.label_38)
        spacerItem39 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_38.addItem(spacerItem39)
        self.acc_name = QtWidgets.QLineEdit(CloudMsg)
        self.acc_name.setObjectName("acc_name")
        self.horizontalLayout_38.addWidget(self.acc_name)
        self.verticalLayout_7.addLayout(self.horizontalLayout_38)
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.label_40 = QtWidgets.QLabel(CloudMsg)
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_39.addWidget(self.label_40)
        spacerItem40 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_39.addItem(spacerItem40)
        self.templateID = QtWidgets.QLineEdit(CloudMsg)
        self.templateID.setObjectName("templateID")
        self.horizontalLayout_39.addWidget(self.templateID)
        self.verticalLayout_7.addLayout(self.horizontalLayout_39)
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.label_41 = QtWidgets.QLabel(CloudMsg)
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_40.addWidget(self.label_41)
        spacerItem41 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_40.addItem(spacerItem41)
        self.extnumber = QtWidgets.QLineEdit(CloudMsg)
        self.extnumber.setObjectName("extnumber")
        self.horizontalLayout_40.addWidget(self.extnumber)
        self.verticalLayout_7.addLayout(self.horizontalLayout_40)
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.label_42 = QtWidgets.QLabel(CloudMsg)
        self.label_42.setObjectName("label_42")
        self.horizontalLayout_41.addWidget(self.label_42)
        spacerItem42 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_41.addItem(spacerItem42)
        self.sign = QtWidgets.QLineEdit(CloudMsg)
        self.sign.setObjectName("sign")
        self.horizontalLayout_41.addWidget(self.sign)
        self.verticalLayout_7.addLayout(self.horizontalLayout_41)
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.label_43 = QtWidgets.QLabel(CloudMsg)
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_42.addWidget(self.label_43)
        spacerItem43 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_42.addItem(spacerItem43)
        self.acc_msgid = QtWidgets.QLineEdit(CloudMsg)
        self.acc_msgid.setObjectName("acc_msgid")
        self.horizontalLayout_42.addWidget(self.acc_msgid)
        self.verticalLayout_7.addLayout(self.horizontalLayout_42)
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.label_44 = QtWidgets.QLabel(CloudMsg)
        self.label_44.setObjectName("label_44")
        self.horizontalLayout_43.addWidget(self.label_44)
        spacerItem44 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_43.addItem(spacerItem44)
        self.mms_title = QtWidgets.QLineEdit(CloudMsg)
        self.mms_title.setObjectName("mms_title")
        self.horizontalLayout_43.addWidget(self.mms_title)
        self.verticalLayout_7.addLayout(self.horizontalLayout_43)
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.label_45 = QtWidgets.QLabel(CloudMsg)
        self.label_45.setObjectName("label_45")
        self.horizontalLayout_44.addWidget(self.label_45)
        spacerItem45 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_44.addItem(spacerItem45)
        self.mms_path = QtWidgets.QLineEdit(CloudMsg)
        self.mms_path.setObjectName("mms_path")
        self.horizontalLayout_44.addWidget(self.mms_path)
        self.verticalLayout_7.addLayout(self.horizontalLayout_44)
        self.horizontalLayout_45 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.label_46 = QtWidgets.QLabel(CloudMsg)
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_45.addWidget(self.label_46)
        spacerItem46 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_45.addItem(spacerItem46)
        self.user_defid = QtWidgets.QLineEdit(CloudMsg)
        self.user_defid.setObjectName("user_defid")
        self.horizontalLayout_45.addWidget(self.user_defid)
        self.verticalLayout_7.addLayout(self.horizontalLayout_45)
        self.gridLayout.addLayout(self.verticalLayout_7, 0, 1, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_39 = QtWidgets.QLabel(CloudMsg)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_2.addWidget(self.label_39)
        self.mobile = QtWidgets.QTextEdit(CloudMsg)
        self.mobile.setObjectName("mobile")
        self.verticalLayout_2.addWidget(self.mobile)
        self.verticalLayout_6.addLayout(self.verticalLayout_2)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_52 = QtWidgets.QLabel(CloudMsg)
        self.label_52.setObjectName("label_52")
        self.verticalLayout_8.addWidget(self.label_52)
        self.paramtemplate = QtWidgets.QTextEdit(CloudMsg)
        self.paramtemplate.setObjectName("paramtemplate")
        self.verticalLayout_8.addWidget(self.paramtemplate)
        self.verticalLayout_6.addLayout(self.verticalLayout_8)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_49 = QtWidgets.QLabel(CloudMsg)
        self.label_49.setObjectName("label_49")
        self.verticalLayout_5.addWidget(self.label_49)
        self.msgtemplate = QtWidgets.QTextEdit(CloudMsg)
        self.msgtemplate.setObjectName("msgtemplate")
        self.verticalLayout_5.addWidget(self.msgtemplate)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.gridLayout.addLayout(self.verticalLayout_6, 0, 2, 2, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_47 = QtWidgets.QLabel(CloudMsg)
        self.label_47.setObjectName("label_47")
        self.verticalLayout_3.addWidget(self.label_47)
        self.message = QtWidgets.QTextEdit(CloudMsg)
        self.message.setObjectName("message")
        self.verticalLayout_3.addWidget(self.message)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 1, 1, 1)

        self.retranslateUi(CloudMsg)
        QtCore.QMetaObject.connectSlotsByName(CloudMsg)

    def retranslateUi(self, CloudMsg):
        _translate = QtCore.QCoreApplication.translate
        CloudMsg.setWindowTitle(_translate("CloudMsg", "Form"))
        self.label.setText(_translate("CloudMsg", "消息级别"))
        self.Priority.setText(_translate("CloudMsg", "0"))
        self.label_2.setText(_translate("CloudMsg", "MsgId"))
        self.MsgId.setText(_translate("CloudMsg", "0"))
        self.label_3.setText(_translate("CloudMsg", "扩展产品"))
        self.ProductExtendId.setText(_translate("CloudMsg", "0"))
        self.label_4.setText(_translate("CloudMsg", "真实发送扩展产品"))
        self.RealProductExtendId.setText(_translate("CloudMsg", "0"))
        self.label_24.setText(_translate("CloudMsg", "开始发送日期"))
        self.StartSendDateTime.setDisplayFormat(_translate("CloudMsg", "yyyy/M/d H:mm:ss"))
        self.label_21.setText(_translate("CloudMsg", "结束发送日期"))
        self.EndSendDateTime.setDisplayFormat(_translate("CloudMsg", "yyyy/M/d H:mm:ss"))
        self.label_22.setText(_translate("CloudMsg", "开始发送时段"))
        self.StartSendTime.setDisplayFormat(_translate("CloudMsg", "yyyy/M/d H:mm:ss"))
        self.label_23.setText(_translate("CloudMsg", "结束发送时段"))
        self.EndSendTime.setDisplayFormat(_translate("CloudMsg", "yyyy/M/d H:mm:ss"))
        self.label_9.setText(_translate("CloudMsg", "计费号码数"))
        self.ChargeQuantity.setText(_translate("CloudMsg", "0"))
        self.label_10.setText(_translate("CloudMsg", "消息状态"))
        self.MsgState.setItemText(0, _translate("CloudMsg", "待审核"))
        self.MsgState.setItemText(1, _translate("CloudMsg", "已审核"))
        self.MsgState.setItemText(2, _translate("CloudMsg", "已驳回"))
        self.MsgState.setItemText(3, _translate("CloudMsg", "已发送"))
        self.MsgState.setItemText(4, _translate("CloudMsg", "全部取消"))
        self.MsgState.setItemText(5, _translate("CloudMsg", "二审"))
        self.MsgState.setItemText(6, _translate("CloudMsg", "完成"))
        self.label_11.setText(_translate("CloudMsg", "信息类型"))
        self.MsgType.setItemText(0, _translate("CloudMsg", "短信"))
        self.MsgType.setItemText(1, _translate("CloudMsg", "彩信"))
        self.label_25.setText(_translate("CloudMsg", "提交时间"))
        self.CommitTime.setDisplayFormat(_translate("CloudMsg", "yyyy/M/d H:mm:ss"))
        self.label_13.setText(_translate("CloudMsg", "包号"))
        self.Package.setText(_translate("CloudMsg", "0"))
        self.label_14.setText(_translate("CloudMsg", "号码内容长度"))
        self.MobilesContentLen.setText(_translate("CloudMsg", "12"))
        self.label_15.setText(_translate("CloudMsg", "信息内容长度"))
        self.MsgContentLen.setText(_translate("CloudMsg", "6"))
        self.label_16.setText(_translate("CloudMsg", "号码个数"))
        self.MobilesCount.setText(_translate("CloudMsg", "1"))
        self.label_17.setText(_translate("CloudMsg", "调度次数"))
        self.DispatchTimes.setText(_translate("CloudMsg", "0"))
        self.label_18.setText(_translate("CloudMsg", "运营商"))
        self.Telcom.setItemText(0, _translate("CloudMsg", "移动"))
        self.Telcom.setItemText(1, _translate("CloudMsg", "联通"))
        self.Telcom.setItemText(2, _translate("CloudMsg", "电信"))
        self.Telcom.setItemText(3, _translate("CloudMsg", "小灵通"))
        self.label_19.setText(_translate("CloudMsg", "号码归属省份"))
        self.ProvinceId.setText(_translate("CloudMsg", "0"))
        self.label_8.setText(_translate("CloudMsg", "号码归属城市"))
        self.CityId.setText(_translate("CloudMsg", "0"))
        self.label_7.setText(_translate("CloudMsg", "是否定位"))
        self.TPCBChecked.setText(_translate("CloudMsg", "0"))
        self.label_6.setText(_translate("CloudMsg", "已发送次数"))
        self.SendedTimes.setText(_translate("CloudMsg", "0"))
        self.label_12.setText(_translate("CloudMsg", "调度失败状态"))
        self.DispatchFailedState.setText(_translate("CloudMsg", "0"))
        self.label_5.setText(_translate("CloudMsg", "提交接口"))
        self.SubmitType.setText(_translate("CloudMsg", "0"))
        self.label_20.setText(_translate("CloudMsg", "模板ID"))
        self.CloudMsgTemplateID.setText(_translate("CloudMsg", "0"))
        self.label_50.setText(_translate("CloudMsg", "提交IP"))
        self.CommitIp.setText(_translate("CloudMsg", "127.0.0.1"))
        self.label_26.setText(_translate("CloudMsg", "旧消息"))
        self.m_old_struct.setText(_translate("CloudMsg", "0"))
        self.label_27.setText(_translate("CloudMsg", "信息总页数"))
        self.pagetotal.setText(_translate("CloudMsg", "0"))
        self.label_28.setText(_translate("CloudMsg", "信息总包数"))
        self.packagetotal.setText(_translate("CloudMsg", "0"))
        self.label_29.setText(_translate("CloudMsg", "信息类型"))
        self.typeComponentParam.setText(_translate("CloudMsg", "0"))
        self.label_30.setText(_translate("CloudMsg", "最后一次资源发送失败id"))
        self.lastFailResourceId.setText(_translate("CloudMsg", "0"))
        self.label_31.setText(_translate("CloudMsg", "失败类型"))
        self.failedType.setItemText(0, _translate("CloudMsg", "成功"))
        self.failedType.setItemText(1, _translate("CloudMsg", "调度失败"))
        self.failedType.setItemText(2, _translate("CloudMsg", "发送失败"))
        self.failedType.setItemText(3, _translate("CloudMsg", "状态报告失败"))
        self.failedType.setItemText(4, _translate("CloudMsg", "黑名单"))
        self.failedType.setItemText(5, _translate("CloudMsg", "无效号码"))
        self.failedType.setItemText(6, _translate("CloudMsg", "人工取消"))
        self.failedType.setItemText(7, _translate("CloudMsg", "信息失效"))
        self.failedType.setItemText(8, _translate("CloudMsg", "提交限量"))
        self.label_37.setText(_translate("CloudMsg", "最后一次调度时间"))
        self.lastDiapatchTime.setDisplayFormat(_translate("CloudMsg", "yyyy/M/d H:mm:ss"))
        self.label_33.setText(_translate("CloudMsg", "资源发送次数"))
        self.resourceSendTimes.setText(_translate("CloudMsg", "0"))
        self.label_34.setText(_translate("CloudMsg", "审核id"))
        self.auditorId.setText(_translate("CloudMsg", "0"))
        self.label_35.setText(_translate("CloudMsg", "发送次数"))
        self.totalSendTimes.setText(_translate("CloudMsg", "0"))
        self.label_36.setText(_translate("CloudMsg", "回执重发的超时时长"))
        self.repResendTimeOut.setText(_translate("CloudMsg", "0"))
        self.label_32.setText(_translate("CloudMsg", "进入调度中心次数"))
        self.innerDispatchTimes.setText(_translate("CloudMsg", "0"))
        self.label_51.setText(_translate("CloudMsg", "扩展组合值"))
        self.extComponentParam.setText(_translate("CloudMsg", "0"))
        self.label_38.setText(_translate("CloudMsg", "提交帐号"))
        self.acc_name.setText(_translate("CloudMsg", "0"))
        self.label_40.setText(_translate("CloudMsg", "运营商模板ID"))
        self.templateID.setText(_translate("CloudMsg", "0"))
        self.label_41.setText(_translate("CloudMsg", "扩展号码"))
        self.extnumber.setText(_translate("CloudMsg", "1069"))
        self.label_42.setText(_translate("CloudMsg", "签名"))
        self.sign.setText(_translate("CloudMsg", "【微网通联】"))
        self.label_43.setText(_translate("CloudMsg", "客户自定义参数"))
        self.acc_msgid.setText(_translate("CloudMsg", "0"))
        self.label_44.setText(_translate("CloudMsg", "彩信标题"))
        self.mms_title.setText(_translate("CloudMsg", "这是标题"))
        self.label_45.setText(_translate("CloudMsg", "彩信存储文件路径"))
        self.mms_path.setText(_translate("CloudMsg", "c://"))
        self.label_46.setText(_translate("CloudMsg", "用户自定义参数"))
        self.user_defid.setText(_translate("CloudMsg", "0"))
        self.label_39.setText(_translate("CloudMsg", "电话号码"))
        self.mobile.setHtml(_translate("CloudMsg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">13000000000</p></body></html>"))
        self.label_52.setText(_translate("CloudMsg", "模板参数"))
        self.paramtemplate.setHtml(_translate("CloudMsg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;</p></body></html>"))
        self.label_49.setText(_translate("CloudMsg", "模板内容"))
        self.msgtemplate.setHtml(_translate("CloudMsg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">不好</p></body></html>"))
        self.label_47.setText(_translate("CloudMsg", "短信内容"))
        self.message.setHtml(_translate("CloudMsg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">你好</p></body></html>"))

