# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Monitor_Cloud.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Monitor_Cloud(object):
    def setupUi(self, Monitor_Cloud):
        Monitor_Cloud.setObjectName("Monitor_Cloud")
        Monitor_Cloud.resize(901, 657)
        self.gridLayout_5 = QtWidgets.QGridLayout(Monitor_Cloud)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox = QtWidgets.QCheckBox(Monitor_Cloud)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)
        self.groupBox = QtWidgets.QGroupBox(Monitor_Cloud)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.lineEdit_ResourceId = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_ResourceId.setObjectName("lineEdit_ResourceId")
        self.verticalLayout_7.addWidget(self.lineEdit_ResourceId)
        self.dateTimeEdit_NotifyTime = QtWidgets.QDateTimeEdit(self.groupBox)
        self.dateTimeEdit_NotifyTime.setObjectName("dateTimeEdit_NotifyTime")
        self.verticalLayout_7.addWidget(self.dateTimeEdit_NotifyTime)
        self.comboBox_RunTimeState = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_RunTimeState.setObjectName("comboBox_RunTimeState")
        self.comboBox_RunTimeState.addItem("")
        self.comboBox_RunTimeState.addItem("")
        self.verticalLayout_7.addWidget(self.comboBox_RunTimeState)
        self.lineEdit_QueueStock = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_QueueStock.setObjectName("lineEdit_QueueStock")
        self.verticalLayout_7.addWidget(self.lineEdit_QueueStock)
        self.lineEdit_lastTimeQueueStock = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_lastTimeQueueStock.setObjectName("lineEdit_lastTimeQueueStock")
        self.verticalLayout_7.addWidget(self.lineEdit_lastTimeQueueStock)
        self.lineEdit_reportTimeInterval = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_reportTimeInterval.setObjectName("lineEdit_reportTimeInterval")
        self.verticalLayout_7.addWidget(self.lineEdit_reportTimeInterval)
        self.lineEdit_submitTotal = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_submitTotal.setObjectName("lineEdit_submitTotal")
        self.verticalLayout_7.addWidget(self.lineEdit_submitTotal)
        self.lineEdit_submitFail = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_submitFail.setObjectName("lineEdit_submitFail")
        self.verticalLayout_7.addWidget(self.lineEdit_submitFail)
        self.lineEdit_reportTotal = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_reportTotal.setObjectName("lineEdit_reportTotal")
        self.verticalLayout_7.addWidget(self.lineEdit_reportTotal)
        self.lineEdit_reportFail = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_reportFail.setObjectName("lineEdit_reportFail")
        self.verticalLayout_7.addWidget(self.lineEdit_reportFail)
        self.gridLayout.addLayout(self.verticalLayout_7, 0, 2, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.verticalLayout_8.addWidget(self.label)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_8.addWidget(self.label_9)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_8.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_8.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_8.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_8.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_8.addWidget(self.label_8)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_8.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_8.addWidget(self.label_2)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_8.addWidget(self.label_10)
        self.gridLayout.addLayout(self.verticalLayout_8, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.gridLayout_5.addLayout(self.verticalLayout, 0, 0, 2, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_2 = QtWidgets.QCheckBox(Monitor_Cloud)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_2.addWidget(self.checkBox_2)
        self.groupBox_2 = QtWidgets.QGroupBox(Monitor_Cloud)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_12.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_12.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_12.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_12.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_12.addWidget(self.label_15)
        self.gridLayout_2.addLayout(self.verticalLayout_12, 0, 0, 1, 1)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.lineEdit_dispatchCenterId = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_dispatchCenterId.setObjectName("lineEdit_dispatchCenterId")
        self.verticalLayout_11.addWidget(self.lineEdit_dispatchCenterId)
        self.lineEdit_totalDispatchCnt = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_totalDispatchCnt.setObjectName("lineEdit_totalDispatchCnt")
        self.verticalLayout_11.addWidget(self.lineEdit_totalDispatchCnt)
        self.lineEdit_succDispatchCnt = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_succDispatchCnt.setObjectName("lineEdit_succDispatchCnt")
        self.verticalLayout_11.addWidget(self.lineEdit_succDispatchCnt)
        self.lineEdit_failDispatchCnt = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_failDispatchCnt.setObjectName("lineEdit_failDispatchCnt")
        self.verticalLayout_11.addWidget(self.lineEdit_failDispatchCnt)
        self.lineEdit_cycleTime = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_cycleTime.setObjectName("lineEdit_cycleTime")
        self.verticalLayout_11.addWidget(self.lineEdit_cycleTime)
        self.gridLayout_2.addLayout(self.verticalLayout_11, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.gridLayout_5.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.checkBox_4 = QtWidgets.QCheckBox(Monitor_Cloud)
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout_6.addWidget(self.checkBox_4)
        self.groupBox_4 = QtWidgets.QGroupBox(Monitor_Cloud)
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lineEdit_resourceId_2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_resourceId_2.setObjectName("lineEdit_resourceId_2")
        self.verticalLayout_4.addWidget(self.lineEdit_resourceId_2)
        self.dateTimeEdit_reportTime = QtWidgets.QDateTimeEdit(self.groupBox_4)
        self.dateTimeEdit_reportTime.setObjectName("dateTimeEdit_reportTime")
        self.verticalLayout_4.addWidget(self.dateTimeEdit_reportTime)
        self.lineEdit_statisticsConfig = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_statisticsConfig.setObjectName("lineEdit_statisticsConfig")
        self.verticalLayout_4.addWidget(self.lineEdit_statisticsConfig)
        self.lineEdit_currentStock = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_currentStock.setObjectName("lineEdit_currentStock")
        self.verticalLayout_4.addWidget(self.lineEdit_currentStock)
        self.lineEdit_lastStock = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_lastStock.setObjectName("lineEdit_lastStock")
        self.verticalLayout_4.addWidget(self.lineEdit_lastStock)
        self.lineEdit_reportTimeInterval_2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_reportTimeInterval_2.setObjectName("lineEdit_reportTimeInterval_2")
        self.verticalLayout_4.addWidget(self.lineEdit_reportTimeInterval_2)
        self.lineEdit_submitTotal_2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_submitTotal_2.setObjectName("lineEdit_submitTotal_2")
        self.verticalLayout_4.addWidget(self.lineEdit_submitTotal_2)
        self.lineEdit_currentSubmitSuccess = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_currentSubmitSuccess.setObjectName("lineEdit_currentSubmitSuccess")
        self.verticalLayout_4.addWidget(self.lineEdit_currentSubmitSuccess)
        self.lineEdit_currentSubmitFail = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_currentSubmitFail.setObjectName("lineEdit_currentSubmitFail")
        self.verticalLayout_4.addWidget(self.lineEdit_currentSubmitFail)
        self.lineEdit_reportTotal_2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_reportTotal_2.setObjectName("lineEdit_reportTotal_2")
        self.verticalLayout_4.addWidget(self.lineEdit_reportTotal_2)
        self.lineEdit_currentReportSuccess = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_currentReportSuccess.setObjectName("lineEdit_currentReportSuccess")
        self.verticalLayout_4.addWidget(self.lineEdit_currentReportSuccess)
        self.lineEdit_currentReportFail = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_currentReportFail.setObjectName("lineEdit_currentReportFail")
        self.verticalLayout_4.addWidget(self.lineEdit_currentReportFail)
        self.lineEdit_moTotal = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_moTotal.setObjectName("lineEdit_moTotal")
        self.verticalLayout_4.addWidget(self.lineEdit_moTotal)
        self.lineEdit_currentMoTotal = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_currentMoTotal.setObjectName("lineEdit_currentMoTotal")
        self.verticalLayout_4.addWidget(self.lineEdit_currentMoTotal)
        self.comboBox_state = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_state.setObjectName("comboBox_state")
        self.comboBox_state.addItem("")
        self.comboBox_state.addItem("")
        self.verticalLayout_4.addWidget(self.comboBox_state)
        self.gridLayout_4.addLayout(self.verticalLayout_4, 0, 2, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_20 = QtWidgets.QLabel(self.groupBox_4)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_5.addWidget(self.label_20)
        self.label_21 = QtWidgets.QLabel(self.groupBox_4)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_5.addWidget(self.label_21)
        self.label_22 = QtWidgets.QLabel(self.groupBox_4)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_5.addWidget(self.label_22)
        self.label_23 = QtWidgets.QLabel(self.groupBox_4)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_5.addWidget(self.label_23)
        self.label_24 = QtWidgets.QLabel(self.groupBox_4)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_5.addWidget(self.label_24)
        self.label_25 = QtWidgets.QLabel(self.groupBox_4)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_5.addWidget(self.label_25)
        self.label_26 = QtWidgets.QLabel(self.groupBox_4)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_5.addWidget(self.label_26)
        self.label_31 = QtWidgets.QLabel(self.groupBox_4)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_5.addWidget(self.label_31)
        self.label_28 = QtWidgets.QLabel(self.groupBox_4)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_5.addWidget(self.label_28)
        self.label_32 = QtWidgets.QLabel(self.groupBox_4)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_5.addWidget(self.label_32)
        self.label_27 = QtWidgets.QLabel(self.groupBox_4)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_5.addWidget(self.label_27)
        self.label_30 = QtWidgets.QLabel(self.groupBox_4)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_5.addWidget(self.label_30)
        self.label_33 = QtWidgets.QLabel(self.groupBox_4)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_5.addWidget(self.label_33)
        self.label_29 = QtWidgets.QLabel(self.groupBox_4)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_5.addWidget(self.label_29)
        self.label_34 = QtWidgets.QLabel(self.groupBox_4)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_5.addWidget(self.label_34)
        self.gridLayout_4.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 0, 1, 1, 1)
        self.verticalLayout_6.addWidget(self.groupBox_4)
        self.gridLayout_5.addLayout(self.verticalLayout_6, 1, 1, 2, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkBox_3 = QtWidgets.QCheckBox(Monitor_Cloud)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout_3.addWidget(self.checkBox_3)
        self.groupBox_3 = QtWidgets.QGroupBox(Monitor_Cloud)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_16 = QtWidgets.QLabel(self.groupBox_3)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_10.addWidget(self.label_16)
        self.label_17 = QtWidgets.QLabel(self.groupBox_3)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_10.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(self.groupBox_3)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_10.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(self.groupBox_3)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_10.addWidget(self.label_19)
        self.gridLayout_3.addLayout(self.verticalLayout_10, 0, 0, 1, 1)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.lineEdit_resourceId = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_resourceId.setObjectName("lineEdit_resourceId")
        self.verticalLayout_9.addWidget(self.lineEdit_resourceId)
        self.lineEdit_succCnt = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_succCnt.setObjectName("lineEdit_succCnt")
        self.verticalLayout_9.addWidget(self.lineEdit_succCnt)
        self.lineEdit_failCnt = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_failCnt.setObjectName("lineEdit_failCnt")
        self.verticalLayout_9.addWidget(self.lineEdit_failCnt)
        self.lineEdit_cycleTime_2 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_cycleTime_2.setObjectName("lineEdit_cycleTime_2")
        self.verticalLayout_9.addWidget(self.lineEdit_cycleTime_2)
        self.gridLayout_3.addLayout(self.verticalLayout_9, 0, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 0, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.gridLayout_5.addLayout(self.verticalLayout_3, 2, 0, 1, 1)

        self.retranslateUi(Monitor_Cloud)
        QtCore.QMetaObject.connectSlotsByName(Monitor_Cloud)

    def retranslateUi(self, Monitor_Cloud):
        _translate = QtCore.QCoreApplication.translate
        Monitor_Cloud.setWindowTitle(_translate("Monitor_Cloud", "Form"))
        self.checkBox.setText(_translate("Monitor_Cloud", "ResourceStateNotify"))
        self.lineEdit_ResourceId.setText(_translate("Monitor_Cloud", "0"))
        self.dateTimeEdit_NotifyTime.setDisplayFormat(_translate("Monitor_Cloud", "yyyy/M/d H:mm:ss"))
        self.comboBox_RunTimeState.setItemText(0, _translate("Monitor_Cloud", "启用"))
        self.comboBox_RunTimeState.setItemText(1, _translate("Monitor_Cloud", "停用"))
        self.lineEdit_QueueStock.setText(_translate("Monitor_Cloud", "0"))
        self.lineEdit_lastTimeQueueStock.setText(_translate("Monitor_Cloud", "0"))
        self.lineEdit_reportTimeInterval.setText(_translate("Monitor_Cloud", "5"))
        self.lineEdit_submitTotal.setText(_translate("Monitor_Cloud", "0"))
        self.lineEdit_submitFail.setText(_translate("Monitor_Cloud", "0"))
        self.lineEdit_reportTotal.setText(_translate("Monitor_Cloud", "0"))
        self.lineEdit_reportFail.setText(_translate("Monitor_Cloud", "0"))
        self.label.setText(_translate("Monitor_Cloud", "资源id"))
        self.label_9.setText(_translate("Monitor_Cloud", "报告时间"))
        self.label_4.setText(_translate("Monitor_Cloud", "资源状态"))
        self.label_5.setText(_translate("Monitor_Cloud", "队列积压数"))
        self.label_6.setText(_translate("Monitor_Cloud", "最后时间积压数"))
        self.label_7.setText(_translate("Monitor_Cloud", "报告频率"))
        self.label_8.setText(_translate("Monitor_Cloud", "提交总数"))
        self.label_3.setText(_translate("Monitor_Cloud", "提交失败"))
        self.label_2.setText(_translate("Monitor_Cloud", "报告总数"))
        self.label_10.setText(_translate("Monitor_Cloud", "报告失败"))
        self.checkBox_2.setText(_translate("Monitor_Cloud", "SDispatchStatistics"))
        self.label_11.setText(_translate("Monitor_Cloud", "调度id"))
        self.label_12.setText(_translate("Monitor_Cloud", "总调度数"))
        self.label_13.setText(_translate("Monitor_Cloud", "调度成功"))
        self.label_14.setText(_translate("Monitor_Cloud", "调度失败"))
        self.label_15.setText(_translate("Monitor_Cloud", "循环次数"))
        self.lineEdit_dispatchCenterId.setText(_translate("Monitor_Cloud", "0"))
        self.lineEdit_totalDispatchCnt.setText(_translate("Monitor_Cloud", "0"))
        self.lineEdit_succDispatchCnt.setText(_translate("Monitor_Cloud", "0"))
        self.lineEdit_failDispatchCnt.setText(_translate("Monitor_Cloud", "0"))
        self.lineEdit_cycleTime.setText(_translate("Monitor_Cloud", "0"))
        self.checkBox_4.setText(_translate("Monitor_Cloud", "SResourceState"))
        self.lineEdit_resourceId_2.setText(_translate("Monitor_Cloud", "0"))
        self.lineEdit_statisticsConfig.setText(_translate("Monitor_Cloud", "0"))
        self.lineEdit_currentStock.setText(_translate("Monitor_Cloud", "0"))
        self.lineEdit_lastStock.setText(_translate("Monitor_Cloud", "0"))
        self.lineEdit_reportTimeInterval_2.setText(_translate("Monitor_Cloud", "5"))
        self.lineEdit_submitTotal_2.setText(_translate("Monitor_Cloud", "0"))
        self.lineEdit_currentSubmitSuccess.setText(_translate("Monitor_Cloud", "0"))
        self.lineEdit_currentSubmitFail.setText(_translate("Monitor_Cloud", "0"))
        self.lineEdit_reportTotal_2.setText(_translate("Monitor_Cloud", "0"))
        self.lineEdit_currentReportSuccess.setText(_translate("Monitor_Cloud", "0"))
        self.lineEdit_currentReportFail.setText(_translate("Monitor_Cloud", "0"))
        self.lineEdit_moTotal.setText(_translate("Monitor_Cloud", "0"))
        self.lineEdit_currentMoTotal.setText(_translate("Monitor_Cloud", "0"))
        self.comboBox_state.setItemText(0, _translate("Monitor_Cloud", "启用"))
        self.comboBox_state.setItemText(1, _translate("Monitor_Cloud", "停用"))
        self.label_20.setText(_translate("Monitor_Cloud", "资源ID"))
        self.label_21.setText(_translate("Monitor_Cloud", "报告时间"))
        self.label_22.setText(_translate("Monitor_Cloud", "配置值"))
        self.label_23.setText(_translate("Monitor_Cloud", "积压数量"))
        self.label_24.setText(_translate("Monitor_Cloud", "上次库存值"))
        self.label_25.setText(_translate("Monitor_Cloud", "报告时间间隔"))
        self.label_26.setText(_translate("Monitor_Cloud", "下行总数"))
        self.label_31.setText(_translate("Monitor_Cloud", "当前下行成功数"))
        self.label_28.setText(_translate("Monitor_Cloud", "当前下行失败数"))
        self.label_32.setText(_translate("Monitor_Cloud", "状态报告总数"))
        self.label_27.setText(_translate("Monitor_Cloud", "当前状态报告成功数"))
        self.label_30.setText(_translate("Monitor_Cloud", "当前状态报告失败数"))
        self.label_33.setText(_translate("Monitor_Cloud", "上行总数"))
        self.label_29.setText(_translate("Monitor_Cloud", "当前上行数"))
        self.label_34.setText(_translate("Monitor_Cloud", "状态"))
        self.checkBox_3.setText(_translate("Monitor_Cloud", "SResComStatistics"))
        self.label_16.setText(_translate("Monitor_Cloud", "资源id"))
        self.label_17.setText(_translate("Monitor_Cloud", "成功数"))
        self.label_18.setText(_translate("Monitor_Cloud", "失败数"))
        self.label_19.setText(_translate("Monitor_Cloud", "循环次数"))
        self.lineEdit_resourceId.setText(_translate("Monitor_Cloud", "0"))
        self.lineEdit_succCnt.setText(_translate("Monitor_Cloud", "0"))
        self.lineEdit_failCnt.setText(_translate("Monitor_Cloud", "0"))
        self.lineEdit_cycleTime_2.setText(_translate("Monitor_Cloud", "0"))

