# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Monitor.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Monitor(object):
    def setupUi(self, Monitor):
        Monitor.setObjectName("Monitor")
        Monitor.resize(1417, 804)
        self.gridLayout_8 = QtWidgets.QGridLayout(Monitor)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Monitor)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lineEdit_id = QtWidgets.QLineEdit(Monitor)
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.horizontalLayout.addWidget(self.lineEdit_id)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.label_3 = QtWidgets.QLabel(Monitor)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.lineEdit_period = QtWidgets.QLineEdit(Monitor)
        self.lineEdit_period.setObjectName("lineEdit_period")
        self.horizontalLayout_3.addWidget(self.lineEdit_period)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_3)
        self.gridLayout_8.addLayout(self.horizontalLayout_2, 0, 0, 1, 2)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.checkBox_SubmitMonitorMsg = QtWidgets.QCheckBox(Monitor)
        self.checkBox_SubmitMonitorMsg.setObjectName("checkBox_SubmitMonitorMsg")
        self.verticalLayout_7.addWidget(self.checkBox_SubmitMonitorMsg)
        self.groupBox_submit = QtWidgets.QGroupBox(Monitor)
        self.groupBox_submit.setTitle("")
        self.groupBox_submit.setObjectName("groupBox_submit")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_submit)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.groupBox_submit)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.lineEdit_fail = QtWidgets.QLineEdit(self.groupBox_submit)
        self.lineEdit_fail.setObjectName("lineEdit_fail")
        self.horizontalLayout_5.addWidget(self.lineEdit_fail)
        self.gridLayout.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_succ = QtWidgets.QLabel(self.groupBox_submit)
        self.label_succ.setObjectName("label_succ")
        self.horizontalLayout_4.addWidget(self.label_succ)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.lineEdit_succ = QtWidgets.QLineEdit(self.groupBox_submit)
        self.lineEdit_succ.setObjectName("lineEdit_succ")
        self.horizontalLayout_4.addWidget(self.lineEdit_succ)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.groupBox_submit)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.lineEdit_fee = QtWidgets.QLineEdit(self.groupBox_submit)
        self.lineEdit_fee.setObjectName("lineEdit_fee")
        self.horizontalLayout_6.addWidget(self.lineEdit_fee)
        self.gridLayout.addLayout(self.horizontalLayout_6, 2, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.groupBox_submit)
        self.gridLayout_8.addLayout(self.verticalLayout_7, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_SResourceState = QtWidgets.QCheckBox(Monitor)
        self.checkBox_SResourceState.setObjectName("checkBox_SResourceState")
        self.verticalLayout.addWidget(self.checkBox_SResourceState)
        self.groupBox_ResState = QtWidgets.QGroupBox(Monitor)
        self.groupBox_ResState.setTitle("")
        self.groupBox_ResState.setObjectName("groupBox_ResState")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_ResState)
        self.gridLayout_3.setContentsMargins(11, 0, -1, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_20 = QtWidgets.QLabel(self.groupBox_ResState)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_21.addWidget(self.label_20)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem6)
        self.lineEdit_submitTotal = QtWidgets.QLineEdit(self.groupBox_ResState)
        self.lineEdit_submitTotal.setObjectName("lineEdit_submitTotal")
        self.horizontalLayout_21.addWidget(self.lineEdit_submitTotal)
        self.gridLayout_3.addLayout(self.horizontalLayout_21, 5, 0, 1, 1)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_16 = QtWidgets.QLabel(self.groupBox_ResState)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_17.addWidget(self.label_16)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem7)
        self.lineEdit_statisticsConfig = QtWidgets.QLineEdit(self.groupBox_ResState)
        self.lineEdit_statisticsConfig.setObjectName("lineEdit_statisticsConfig")
        self.horizontalLayout_17.addWidget(self.lineEdit_statisticsConfig)
        self.gridLayout_3.addLayout(self.horizontalLayout_17, 1, 0, 1, 1)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_25 = QtWidgets.QLabel(self.groupBox_ResState)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_26.addWidget(self.label_25)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem8)
        self.lineEdit_moTotal = QtWidgets.QLineEdit(self.groupBox_ResState)
        self.lineEdit_moTotal.setObjectName("lineEdit_moTotal")
        self.horizontalLayout_26.addWidget(self.lineEdit_moTotal)
        self.gridLayout_3.addLayout(self.horizontalLayout_26, 11, 0, 1, 1)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_18 = QtWidgets.QLabel(self.groupBox_ResState)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_19.addWidget(self.label_18)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem9)
        self.lineEdit_lastStock = QtWidgets.QLineEdit(self.groupBox_ResState)
        self.lineEdit_lastStock.setObjectName("lineEdit_lastStock")
        self.horizontalLayout_19.addWidget(self.lineEdit_lastStock)
        self.gridLayout_3.addLayout(self.horizontalLayout_19, 3, 0, 1, 1)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_22 = QtWidgets.QLabel(self.groupBox_ResState)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_23.addWidget(self.label_22)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem10)
        self.lineEdit_currentSubmitFail = QtWidgets.QLineEdit(self.groupBox_ResState)
        self.lineEdit_currentSubmitFail.setObjectName("lineEdit_currentSubmitFail")
        self.horizontalLayout_23.addWidget(self.lineEdit_currentSubmitFail)
        self.gridLayout_3.addLayout(self.horizontalLayout_23, 7, 0, 1, 1)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_23 = QtWidgets.QLabel(self.groupBox_ResState)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_24.addWidget(self.label_23)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem11)
        self.lineEdit_currentReportSuccess = QtWidgets.QLineEdit(self.groupBox_ResState)
        self.lineEdit_currentReportSuccess.setObjectName("lineEdit_currentReportSuccess")
        self.horizontalLayout_24.addWidget(self.lineEdit_currentReportSuccess)
        self.gridLayout_3.addLayout(self.horizontalLayout_24, 9, 0, 1, 1)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_19 = QtWidgets.QLabel(self.groupBox_ResState)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_20.addWidget(self.label_19)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem12)
        self.lineEdit_reportTimeInterval = QtWidgets.QLineEdit(self.groupBox_ResState)
        self.lineEdit_reportTimeInterval.setObjectName("lineEdit_reportTimeInterval")
        self.horizontalLayout_20.addWidget(self.lineEdit_reportTimeInterval)
        self.gridLayout_3.addLayout(self.horizontalLayout_20, 4, 0, 1, 1)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_21 = QtWidgets.QLabel(self.groupBox_ResState)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_22.addWidget(self.label_21)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem13)
        self.lineEdit_currentSubmitSuccess = QtWidgets.QLineEdit(self.groupBox_ResState)
        self.lineEdit_currentSubmitSuccess.setObjectName("lineEdit_currentSubmitSuccess")
        self.horizontalLayout_22.addWidget(self.lineEdit_currentSubmitSuccess)
        self.gridLayout_3.addLayout(self.horizontalLayout_22, 6, 0, 1, 1)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_17 = QtWidgets.QLabel(self.groupBox_ResState)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_18.addWidget(self.label_17)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem14)
        self.lineEdit_currentStock = QtWidgets.QLineEdit(self.groupBox_ResState)
        self.lineEdit_currentStock.setObjectName("lineEdit_currentStock")
        self.horizontalLayout_18.addWidget(self.lineEdit_currentStock)
        self.gridLayout_3.addLayout(self.horizontalLayout_18, 2, 0, 1, 1)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_15 = QtWidgets.QLabel(self.groupBox_ResState)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_16.addWidget(self.label_15)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem15)
        self.lineEdit_resid = QtWidgets.QLineEdit(self.groupBox_ResState)
        self.lineEdit_resid.setObjectName("lineEdit_resid")
        self.horizontalLayout_16.addWidget(self.lineEdit_resid)
        self.gridLayout_3.addLayout(self.horizontalLayout_16, 0, 0, 1, 1)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_26 = QtWidgets.QLabel(self.groupBox_ResState)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_27.addWidget(self.label_26)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem16)
        self.lineEdit_currentMoTotal = QtWidgets.QLineEdit(self.groupBox_ResState)
        self.lineEdit_currentMoTotal.setObjectName("lineEdit_currentMoTotal")
        self.horizontalLayout_27.addWidget(self.lineEdit_currentMoTotal)
        self.gridLayout_3.addLayout(self.horizontalLayout_27, 12, 0, 1, 1)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_27 = QtWidgets.QLabel(self.groupBox_ResState)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_28.addWidget(self.label_27)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem17)
        self.lineEdit_state = QtWidgets.QLineEdit(self.groupBox_ResState)
        self.lineEdit_state.setObjectName("lineEdit_state")
        self.horizontalLayout_28.addWidget(self.lineEdit_state)
        self.gridLayout_3.addLayout(self.horizontalLayout_28, 13, 0, 1, 1)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_24 = QtWidgets.QLabel(self.groupBox_ResState)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_25.addWidget(self.label_24)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem18)
        self.lineEdit_currentReportFail = QtWidgets.QLineEdit(self.groupBox_ResState)
        self.lineEdit_currentReportFail.setObjectName("lineEdit_currentReportFail")
        self.horizontalLayout_25.addWidget(self.lineEdit_currentReportFail)
        self.gridLayout_3.addLayout(self.horizontalLayout_25, 10, 0, 1, 1)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_28 = QtWidgets.QLabel(self.groupBox_ResState)
        self.label_28.setWordWrap(False)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_29.addWidget(self.label_28)
        spacerItem19 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem19)
        self.lineEdit_reportTotal = QtWidgets.QLineEdit(self.groupBox_ResState)
        self.lineEdit_reportTotal.setObjectName("lineEdit_reportTotal")
        self.horizontalLayout_29.addWidget(self.lineEdit_reportTotal)
        self.gridLayout_3.addLayout(self.horizontalLayout_29, 8, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_ResState)
        self.gridLayout_8.addLayout(self.verticalLayout, 1, 1, 3, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_DispatchMonitorMsg = QtWidgets.QCheckBox(Monitor)
        self.checkBox_DispatchMonitorMsg.setObjectName("checkBox_DispatchMonitorMsg")
        self.verticalLayout_2.addWidget(self.checkBox_DispatchMonitorMsg)
        self.groupBox_2 = QtWidgets.QGroupBox(Monitor)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tableWidget_dispatch = QtWidgets.QTableWidget(self.groupBox_2)
        self.tableWidget_dispatch.setMinimumSize(QtCore.QSize(451, 0))
        self.tableWidget_dispatch.setMaximumSize(QtCore.QSize(451, 16777215))
        self.tableWidget_dispatch.setRowCount(36)
        self.tableWidget_dispatch.setObjectName("tableWidget_dispatch")
        self.tableWidget_dispatch.setColumnCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget_dispatch.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget_dispatch.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget_dispatch.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(2, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(3, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(4, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(4, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(5, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(5, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(6, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(6, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(6, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(7, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(7, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(7, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(8, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(8, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(8, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(8, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(9, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(9, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(9, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(9, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(10, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(10, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(10, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(10, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(11, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(11, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(11, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(11, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(12, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(12, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(12, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(12, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(12, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(13, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(13, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(13, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(13, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(13, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(14, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(14, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(14, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(14, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(14, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(15, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(15, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(15, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(15, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(15, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(16, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(16, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(16, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(16, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(16, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(17, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(17, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(17, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(17, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(17, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(18, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(18, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(18, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(18, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(18, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(19, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(19, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(19, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(19, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(19, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(20, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(20, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(20, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(20, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(20, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(21, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(21, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(21, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(21, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(21, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(22, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(22, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(22, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(22, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(22, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(23, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(23, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(23, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(23, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(23, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(24, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(24, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(24, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(24, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(24, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(25, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(25, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(25, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(25, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(25, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(26, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(26, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(26, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(26, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(26, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(27, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(27, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(27, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(27, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(27, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(28, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(28, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(28, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(28, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(28, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(29, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(29, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(29, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(29, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(29, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(30, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(30, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(30, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(30, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(30, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(31, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(31, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(31, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(31, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(31, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(32, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(32, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(32, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(32, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(33, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(33, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(33, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(33, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(34, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(34, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(34, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(34, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(35, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(35, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_dispatch.setItem(35, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dispatch.setItem(35, 5, item)
        self.tableWidget_dispatch.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_dispatch.horizontalHeader().setDefaultSectionSize(70)
        self.tableWidget_dispatch.verticalHeader().setVisible(False)
        self.tableWidget_dispatch.verticalHeader().setHighlightSections(True)
        self.tableWidget_dispatch.verticalHeader().setMinimumSectionSize(18)
        self.gridLayout_2.addWidget(self.tableWidget_dispatch, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.gridLayout_8.addLayout(self.verticalLayout_2, 1, 2, 3, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkBox_HisPreDealMonitorData = QtWidgets.QCheckBox(Monitor)
        self.checkBox_HisPreDealMonitorData.setObjectName("checkBox_HisPreDealMonitorData")
        self.verticalLayout_3.addWidget(self.checkBox_HisPreDealMonitorData)
        self.groupBox_Hispre = QtWidgets.QGroupBox(Monitor)
        self.groupBox_Hispre.setTitle("")
        self.groupBox_Hispre.setObjectName("groupBox_Hispre")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_Hispre)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.label_32 = QtWidgets.QLabel(self.groupBox_Hispre)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_33.addWidget(self.label_32)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_33.addItem(spacerItem20)
        self.lineEdit_sndFldRsndCnt = QtWidgets.QLineEdit(self.groupBox_Hispre)
        self.lineEdit_sndFldRsndCnt.setObjectName("lineEdit_sndFldRsndCnt")
        self.horizontalLayout_33.addWidget(self.lineEdit_sndFldRsndCnt)
        self.gridLayout_4.addLayout(self.horizontalLayout_33, 3, 0, 1, 1)
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.label_35 = QtWidgets.QLabel(self.groupBox_Hispre)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_36.addWidget(self.label_35)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_36.addItem(spacerItem21)
        self.lineEdit_repFldRsndCnt = QtWidgets.QLineEdit(self.groupBox_Hispre)
        self.lineEdit_repFldRsndCnt.setObjectName("lineEdit_repFldRsndCnt")
        self.horizontalLayout_36.addWidget(self.lineEdit_repFldRsndCnt)
        self.gridLayout_4.addLayout(self.horizontalLayout_36, 4, 0, 1, 1)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_30 = QtWidgets.QLabel(self.groupBox_Hispre)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_31.addWidget(self.label_30)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem22)
        self.lineEdit_recCnt = QtWidgets.QLineEdit(self.groupBox_Hispre)
        self.lineEdit_recCnt.setObjectName("lineEdit_recCnt")
        self.horizontalLayout_31.addWidget(self.lineEdit_recCnt)
        self.gridLayout_4.addLayout(self.horizontalLayout_31, 0, 0, 1, 1)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.label_31 = QtWidgets.QLabel(self.groupBox_Hispre)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_32.addWidget(self.label_31)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem23)
        self.lineEdit_perRcvCnt = QtWidgets.QLineEdit(self.groupBox_Hispre)
        self.lineEdit_perRcvCnt.setObjectName("lineEdit_perRcvCnt")
        self.horizontalLayout_32.addWidget(self.lineEdit_perRcvCnt)
        self.gridLayout_4.addLayout(self.horizontalLayout_32, 1, 0, 1, 1)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.label_33 = QtWidgets.QLabel(self.groupBox_Hispre)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_34.addWidget(self.label_33)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem24)
        self.lineEdit_mtcnCnt = QtWidgets.QLineEdit(self.groupBox_Hispre)
        self.lineEdit_mtcnCnt.setObjectName("lineEdit_mtcnCnt")
        self.horizontalLayout_34.addWidget(self.lineEdit_mtcnCnt)
        self.gridLayout_4.addLayout(self.horizontalLayout_34, 2, 0, 1, 1)
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.label_36 = QtWidgets.QLabel(self.groupBox_Hispre)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_37.addWidget(self.label_36)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_37.addItem(spacerItem25)
        self.lineEdit_repTmoutRsndCnt = QtWidgets.QLineEdit(self.groupBox_Hispre)
        self.lineEdit_repTmoutRsndCnt.setObjectName("lineEdit_repTmoutRsndCnt")
        self.horizontalLayout_37.addWidget(self.lineEdit_repTmoutRsndCnt)
        self.gridLayout_4.addLayout(self.horizontalLayout_37, 5, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_Hispre)
        self.gridLayout_8.addLayout(self.verticalLayout_3, 2, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.checkBox_HisCenterMonitor = QtWidgets.QCheckBox(Monitor)
        self.checkBox_HisCenterMonitor.setObjectName("checkBox_HisCenterMonitor")
        self.verticalLayout_4.addWidget(self.checkBox_HisCenterMonitor)
        self.groupBox_HisCenter = QtWidgets.QGroupBox(Monitor)
        self.groupBox_HisCenter.setTitle("")
        self.groupBox_HisCenter.setObjectName("groupBox_HisCenter")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_HisCenter)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.label_40 = QtWidgets.QLabel(self.groupBox_HisCenter)
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_41.addWidget(self.label_40)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_41.addItem(spacerItem26)
        self.lineEdit_directInstCnt = QtWidgets.QLineEdit(self.groupBox_HisCenter)
        self.lineEdit_directInstCnt.setObjectName("lineEdit_directInstCnt")
        self.horizontalLayout_41.addWidget(self.lineEdit_directInstCnt)
        self.gridLayout_5.addLayout(self.horizontalLayout_41, 2, 0, 1, 1)
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.label_41 = QtWidgets.QLabel(self.groupBox_HisCenter)
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_42.addWidget(self.label_41)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_42.addItem(spacerItem27)
        self.lineEdit_repMtchCnt = QtWidgets.QLineEdit(self.groupBox_HisCenter)
        self.lineEdit_repMtchCnt.setObjectName("lineEdit_repMtchCnt")
        self.horizontalLayout_42.addWidget(self.lineEdit_repMtchCnt)
        self.gridLayout_5.addLayout(self.horizontalLayout_42, 3, 0, 1, 1)
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.label_38 = QtWidgets.QLabel(self.groupBox_HisCenter)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_39.addWidget(self.label_38)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_39.addItem(spacerItem28)
        self.lineEdit_preCnt = QtWidgets.QLineEdit(self.groupBox_HisCenter)
        self.lineEdit_preCnt.setObjectName("lineEdit_preCnt")
        self.horizontalLayout_39.addWidget(self.lineEdit_preCnt)
        self.gridLayout_5.addLayout(self.horizontalLayout_39, 0, 0, 1, 1)
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.label_39 = QtWidgets.QLabel(self.groupBox_HisCenter)
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_40.addWidget(self.label_39)
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_40.addItem(spacerItem29)
        self.lineEdit_rcvMsgCnt = QtWidgets.QLineEdit(self.groupBox_HisCenter)
        self.lineEdit_rcvMsgCnt.setObjectName("lineEdit_rcvMsgCnt")
        self.horizontalLayout_40.addWidget(self.lineEdit_rcvMsgCnt)
        self.gridLayout_5.addLayout(self.horizontalLayout_40, 1, 0, 1, 1)
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.label_42 = QtWidgets.QLabel(self.groupBox_HisCenter)
        self.label_42.setObjectName("label_42")
        self.horizontalLayout_43.addWidget(self.label_42)
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_43.addItem(spacerItem30)
        self.lineEdit_repRtryMtchCnt = QtWidgets.QLineEdit(self.groupBox_HisCenter)
        self.lineEdit_repRtryMtchCnt.setObjectName("lineEdit_repRtryMtchCnt")
        self.horizontalLayout_43.addWidget(self.lineEdit_repRtryMtchCnt)
        self.gridLayout_5.addLayout(self.horizontalLayout_43, 4, 0, 1, 1)
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.label_43 = QtWidgets.QLabel(self.groupBox_HisCenter)
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_44.addWidget(self.label_43)
        spacerItem31 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_44.addItem(spacerItem31)
        self.lineEdit_repDismtchCnt = QtWidgets.QLineEdit(self.groupBox_HisCenter)
        self.lineEdit_repDismtchCnt.setObjectName("lineEdit_repDismtchCnt")
        self.horizontalLayout_44.addWidget(self.lineEdit_repDismtchCnt)
        self.gridLayout_5.addLayout(self.horizontalLayout_44, 5, 0, 1, 1)
        self.horizontalLayout_45 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.label_44 = QtWidgets.QLabel(self.groupBox_HisCenter)
        self.label_44.setObjectName("label_44")
        self.horizontalLayout_45.addWidget(self.label_44)
        spacerItem32 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_45.addItem(spacerItem32)
        self.lineEdit_moMsgCnt = QtWidgets.QLineEdit(self.groupBox_HisCenter)
        self.lineEdit_moMsgCnt.setObjectName("lineEdit_moMsgCnt")
        self.horizontalLayout_45.addWidget(self.lineEdit_moMsgCnt)
        self.gridLayout_5.addLayout(self.horizontalLayout_45, 6, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_HisCenter)
        self.gridLayout_8.addLayout(self.verticalLayout_4, 3, 0, 2, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.checkBox_SHeartBeat = QtWidgets.QCheckBox(Monitor)
        self.checkBox_SHeartBeat.setObjectName("checkBox_SHeartBeat")
        self.verticalLayout_5.addWidget(self.checkBox_SHeartBeat)
        self.groupBox_HeartBeat = QtWidgets.QGroupBox(Monitor)
        self.groupBox_HeartBeat.setTitle("")
        self.groupBox_HeartBeat.setObjectName("groupBox_HeartBeat")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_HeartBeat)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.label_45 = QtWidgets.QLabel(self.groupBox_HeartBeat)
        self.label_45.setObjectName("label_45")
        self.horizontalLayout_46.addWidget(self.label_45)
        spacerItem33 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_46.addItem(spacerItem33)
        self.lineEdit_timeInterval = QtWidgets.QLineEdit(self.groupBox_HeartBeat)
        self.lineEdit_timeInterval.setObjectName("lineEdit_timeInterval")
        self.horizontalLayout_46.addWidget(self.lineEdit_timeInterval)
        self.gridLayout_6.addLayout(self.horizontalLayout_46, 0, 0, 1, 1)
        self.horizontalLayout_49 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_49.setObjectName("horizontalLayout_49")
        self.label_48 = QtWidgets.QLabel(self.groupBox_HeartBeat)
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_49.addWidget(self.label_48)
        spacerItem34 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_49.addItem(spacerItem34)
        self.lineEdit_alarm_module = QtWidgets.QLineEdit(self.groupBox_HeartBeat)
        self.lineEdit_alarm_module.setObjectName("lineEdit_alarm_module")
        self.horizontalLayout_49.addWidget(self.lineEdit_alarm_module)
        self.gridLayout_6.addLayout(self.horizontalLayout_49, 2, 0, 1, 1)
        self.horizontalLayout_48 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_48.setObjectName("horizontalLayout_48")
        self.label_47 = QtWidgets.QLabel(self.groupBox_HeartBeat)
        self.label_47.setObjectName("label_47")
        self.horizontalLayout_48.addWidget(self.label_47)
        spacerItem35 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_48.addItem(spacerItem35)
        self.lineEdit_stat = QtWidgets.QLineEdit(self.groupBox_HeartBeat)
        self.lineEdit_stat.setObjectName("lineEdit_stat")
        self.horizontalLayout_48.addWidget(self.lineEdit_stat)
        self.gridLayout_6.addLayout(self.horizontalLayout_48, 1, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_HeartBeat)
        self.gridLayout_8.addLayout(self.verticalLayout_5, 4, 1, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.checkBox_log = QtWidgets.QCheckBox(Monitor)
        self.checkBox_log.setObjectName("checkBox_log")
        self.verticalLayout_6.addWidget(self.checkBox_log)
        self.groupBox_log = QtWidgets.QGroupBox(Monitor)
        self.groupBox_log.setTitle("")
        self.groupBox_log.setObjectName("groupBox_log")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_log)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout_50 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_50.setObjectName("horizontalLayout_50")
        self.label_49 = QtWidgets.QLabel(self.groupBox_log)
        self.label_49.setObjectName("label_49")
        self.horizontalLayout_50.addWidget(self.label_49)
        spacerItem36 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_50.addItem(spacerItem36)
        self.lineEdit_level = QtWidgets.QLineEdit(self.groupBox_log)
        self.lineEdit_level.setObjectName("lineEdit_level")
        self.horizontalLayout_50.addWidget(self.lineEdit_level)
        self.gridLayout_7.addLayout(self.horizontalLayout_50, 0, 0, 1, 1)
        self.horizontalLayout_51 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_51.setObjectName("horizontalLayout_51")
        self.label_50 = QtWidgets.QLabel(self.groupBox_log)
        self.label_50.setObjectName("label_50")
        self.horizontalLayout_51.addWidget(self.label_50)
        spacerItem37 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_51.addItem(spacerItem37)
        self.lineEdit_ip = QtWidgets.QLineEdit(self.groupBox_log)
        self.lineEdit_ip.setObjectName("lineEdit_ip")
        self.horizontalLayout_51.addWidget(self.lineEdit_ip)
        self.gridLayout_7.addLayout(self.horizontalLayout_51, 1, 0, 1, 1)
        self.horizontalLayout_53 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_53.setObjectName("horizontalLayout_53")
        self.label_52 = QtWidgets.QLabel(self.groupBox_log)
        self.label_52.setObjectName("label_52")
        self.horizontalLayout_53.addWidget(self.label_52)
        spacerItem38 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_53.addItem(spacerItem38)
        self.lineEdit_name = QtWidgets.QLineEdit(self.groupBox_log)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.horizontalLayout_53.addWidget(self.lineEdit_name)
        self.gridLayout_7.addLayout(self.horizontalLayout_53, 2, 0, 1, 1)
        self.horizontalLayout_54 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_54.setObjectName("horizontalLayout_54")
        self.label_53 = QtWidgets.QLabel(self.groupBox_log)
        self.label_53.setObjectName("label_53")
        self.horizontalLayout_54.addWidget(self.label_53)
        spacerItem39 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_54.addItem(spacerItem39)
        self.lineEdit_msg = QtWidgets.QLineEdit(self.groupBox_log)
        self.lineEdit_msg.setObjectName("lineEdit_msg")
        self.horizontalLayout_54.addWidget(self.lineEdit_msg)
        self.gridLayout_7.addLayout(self.horizontalLayout_54, 3, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.groupBox_log)
        self.gridLayout_8.addLayout(self.verticalLayout_6, 4, 2, 1, 1)

        self.retranslateUi(Monitor)
        QtCore.QMetaObject.connectSlotsByName(Monitor)

    def retranslateUi(self, Monitor):
        _translate = QtCore.QCoreApplication.translate
        Monitor.setWindowTitle(_translate("Monitor", "Form"))
        self.label.setText(_translate("Monitor", "id"))
        self.lineEdit_id.setText(_translate("Monitor", "0"))
        self.label_3.setText(_translate("Monitor", "period"))
        self.lineEdit_period.setText(_translate("Monitor", "5"))
        self.checkBox_SubmitMonitorMsg.setText(_translate("Monitor", "SubmitMonitorMsg"))
        self.label_4.setText(_translate("Monitor", "_fail    "))
        self.lineEdit_fail.setText(_translate("Monitor", "0"))
        self.label_succ.setText(_translate("Monitor", "_succ    "))
        self.lineEdit_succ.setText(_translate("Monitor", "0"))
        self.label_5.setText(_translate("Monitor", "_succ_fee"))
        self.lineEdit_fee.setText(_translate("Monitor", "0"))
        self.checkBox_SResourceState.setText(_translate("Monitor", "SResourceState"))
        self.label_20.setText(_translate("Monitor", "submitTotal         "))
        self.lineEdit_submitTotal.setText(_translate("Monitor", "0"))
        self.label_16.setText(_translate("Monitor", "statisticsConfig    "))
        self.lineEdit_statisticsConfig.setText(_translate("Monitor", "0"))
        self.label_25.setText(_translate("Monitor", "moTotal             "))
        self.lineEdit_moTotal.setText(_translate("Monitor", "0"))
        self.label_18.setText(_translate("Monitor", "lastStock           "))
        self.lineEdit_lastStock.setText(_translate("Monitor", "0"))
        self.label_22.setText(_translate("Monitor", "currentSubmitFail   "))
        self.lineEdit_currentSubmitFail.setText(_translate("Monitor", "0"))
        self.label_23.setText(_translate("Monitor", "currentReportSuccess"))
        self.lineEdit_currentReportSuccess.setText(_translate("Monitor", "0"))
        self.label_19.setText(_translate("Monitor", "reportTimeInterval  "))
        self.lineEdit_reportTimeInterval.setText(_translate("Monitor", "0"))
        self.label_21.setText(_translate("Monitor", "currentSubmitSuccess"))
        self.lineEdit_currentSubmitSuccess.setText(_translate("Monitor", "0"))
        self.label_17.setText(_translate("Monitor", "currentStock        "))
        self.lineEdit_currentStock.setText(_translate("Monitor", "0"))
        self.label_15.setText(_translate("Monitor", "resid               "))
        self.lineEdit_resid.setText(_translate("Monitor", "0"))
        self.label_26.setText(_translate("Monitor", "currentMoTotal      "))
        self.lineEdit_currentMoTotal.setText(_translate("Monitor", "0"))
        self.label_27.setText(_translate("Monitor", "state               "))
        self.lineEdit_state.setText(_translate("Monitor", "0"))
        self.label_24.setText(_translate("Monitor", "currentReportFail   "))
        self.lineEdit_currentReportFail.setText(_translate("Monitor", "0"))
        self.label_28.setText(_translate("Monitor", "reportTotal  "))
        self.lineEdit_reportTotal.setText(_translate("Monitor", "0"))
        self.checkBox_DispatchMonitorMsg.setText(_translate("Monitor", "DispatchMonitorMsg"))
        item = self.tableWidget_dispatch.horizontalHeaderItem(0)
        item.setText(_translate("Monitor", "调度状态"))
        item = self.tableWidget_dispatch.horizontalHeaderItem(1)
        item.setText(_translate("Monitor", "value"))
        item = self.tableWidget_dispatch.horizontalHeaderItem(2)
        item.setText(_translate("Monitor", "运营商"))
        item = self.tableWidget_dispatch.horizontalHeaderItem(3)
        item.setText(_translate("Monitor", "value"))
        item = self.tableWidget_dispatch.horizontalHeaderItem(4)
        item.setText(_translate("Monitor", "省份"))
        item = self.tableWidget_dispatch.horizontalHeaderItem(5)
        item.setText(_translate("Monitor", "value"))
        __sortingEnabled = self.tableWidget_dispatch.isSortingEnabled()
        self.tableWidget_dispatch.setSortingEnabled(False)
        item = self.tableWidget_dispatch.item(0, 0)
        item.setText(_translate("Monitor", "0"))
        item.setToolTip(_translate("Monitor", "0：调度成功\n"
"1：调度的产品未开启\n"
"2：信息过期\n"
"3：扩展产品未配置\n"
"4：资源实时运行未开启\n"
"5：资源在管理平台未开启\n"
"6：调度时间不符合资源发送时段\n"
"7：扩展产品配置的资源不存在\n"
"8：库存不足\n"
"9：当前时间段早于信息开始时间或晚于结束时间\n"
"10：限量不可调度\n"
"11：短信内容长度超过资源最大长度\n"
"12：不支持的签名\n"
"13：发送到的资源消息队列失败"))
        item = self.tableWidget_dispatch.item(0, 1)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(0, 2)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(0, 3)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(0, 4)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(0, 5)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(1, 0)
        item.setText(_translate("Monitor", "1"))
        item = self.tableWidget_dispatch.item(1, 1)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(1, 2)
        item.setText(_translate("Monitor", "1"))
        item = self.tableWidget_dispatch.item(1, 3)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(1, 4)
        item.setText(_translate("Monitor", "1"))
        item = self.tableWidget_dispatch.item(1, 5)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(2, 0)
        item.setText(_translate("Monitor", "2"))
        item = self.tableWidget_dispatch.item(2, 1)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(2, 2)
        item.setText(_translate("Monitor", "2"))
        item = self.tableWidget_dispatch.item(2, 3)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(2, 4)
        item.setText(_translate("Monitor", "2"))
        item = self.tableWidget_dispatch.item(2, 5)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(3, 0)
        item.setText(_translate("Monitor", "3"))
        item = self.tableWidget_dispatch.item(3, 1)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(3, 2)
        item.setText(_translate("Monitor", "3"))
        item = self.tableWidget_dispatch.item(3, 3)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(3, 4)
        item.setText(_translate("Monitor", "3"))
        item = self.tableWidget_dispatch.item(3, 5)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(4, 0)
        item.setText(_translate("Monitor", "4"))
        item = self.tableWidget_dispatch.item(4, 1)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(4, 2)
        item.setText(_translate("Monitor", "4"))
        item = self.tableWidget_dispatch.item(4, 3)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(4, 4)
        item.setText(_translate("Monitor", "4"))
        item = self.tableWidget_dispatch.item(4, 5)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(5, 0)
        item.setText(_translate("Monitor", "5"))
        item = self.tableWidget_dispatch.item(5, 1)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(5, 2)
        item.setText(_translate("Monitor", "5"))
        item = self.tableWidget_dispatch.item(5, 3)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(5, 4)
        item.setText(_translate("Monitor", "5"))
        item = self.tableWidget_dispatch.item(5, 5)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(6, 0)
        item.setText(_translate("Monitor", "6"))
        item = self.tableWidget_dispatch.item(6, 1)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(6, 2)
        item.setText(_translate("Monitor", "6"))
        item = self.tableWidget_dispatch.item(6, 3)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(6, 4)
        item.setText(_translate("Monitor", "6"))
        item = self.tableWidget_dispatch.item(6, 5)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(7, 0)
        item.setText(_translate("Monitor", "7"))
        item = self.tableWidget_dispatch.item(7, 1)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(7, 2)
        item.setText(_translate("Monitor", "7"))
        item = self.tableWidget_dispatch.item(7, 3)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(7, 4)
        item.setText(_translate("Monitor", "7"))
        item = self.tableWidget_dispatch.item(7, 5)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(8, 0)
        item.setText(_translate("Monitor", "8"))
        item = self.tableWidget_dispatch.item(8, 1)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(8, 4)
        item.setText(_translate("Monitor", "8"))
        item = self.tableWidget_dispatch.item(8, 5)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(9, 0)
        item.setText(_translate("Monitor", "9"))
        item = self.tableWidget_dispatch.item(9, 1)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(9, 4)
        item.setText(_translate("Monitor", "9"))
        item = self.tableWidget_dispatch.item(9, 5)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(10, 0)
        item.setText(_translate("Monitor", "10"))
        item = self.tableWidget_dispatch.item(10, 1)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(10, 4)
        item.setText(_translate("Monitor", "10"))
        item = self.tableWidget_dispatch.item(10, 5)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(11, 0)
        item.setText(_translate("Monitor", "11"))
        item = self.tableWidget_dispatch.item(11, 1)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(11, 4)
        item.setText(_translate("Monitor", "11"))
        item = self.tableWidget_dispatch.item(11, 5)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(12, 0)
        item.setText(_translate("Monitor", "12"))
        item = self.tableWidget_dispatch.item(12, 1)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(12, 4)
        item.setText(_translate("Monitor", "12"))
        item = self.tableWidget_dispatch.item(12, 5)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(13, 0)
        item.setText(_translate("Monitor", "13"))
        item = self.tableWidget_dispatch.item(13, 1)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(13, 4)
        item.setText(_translate("Monitor", "13"))
        item = self.tableWidget_dispatch.item(13, 5)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(14, 0)
        item.setText(_translate("Monitor", "14"))
        item = self.tableWidget_dispatch.item(14, 1)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(14, 4)
        item.setText(_translate("Monitor", "14"))
        item = self.tableWidget_dispatch.item(14, 5)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(15, 0)
        item.setText(_translate("Monitor", "15"))
        item = self.tableWidget_dispatch.item(15, 1)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(15, 4)
        item.setText(_translate("Monitor", "15"))
        item = self.tableWidget_dispatch.item(15, 5)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(16, 0)
        item.setText(_translate("Monitor", "16"))
        item = self.tableWidget_dispatch.item(16, 1)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(16, 4)
        item.setText(_translate("Monitor", "16"))
        item = self.tableWidget_dispatch.item(16, 5)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(17, 0)
        item.setText(_translate("Monitor", "17"))
        item = self.tableWidget_dispatch.item(17, 1)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(17, 4)
        item.setText(_translate("Monitor", "17"))
        item = self.tableWidget_dispatch.item(17, 5)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(18, 0)
        item.setText(_translate("Monitor", "18"))
        item = self.tableWidget_dispatch.item(18, 1)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(18, 4)
        item.setText(_translate("Monitor", "18"))
        item = self.tableWidget_dispatch.item(18, 5)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(19, 0)
        item.setText(_translate("Monitor", "19"))
        item = self.tableWidget_dispatch.item(19, 1)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(19, 4)
        item.setText(_translate("Monitor", "19"))
        item = self.tableWidget_dispatch.item(19, 5)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(20, 0)
        item.setText(_translate("Monitor", "20"))
        item = self.tableWidget_dispatch.item(20, 1)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(20, 4)
        item.setText(_translate("Monitor", "20"))
        item = self.tableWidget_dispatch.item(20, 5)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(21, 0)
        item.setText(_translate("Monitor", "21"))
        item = self.tableWidget_dispatch.item(21, 1)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(21, 4)
        item.setText(_translate("Monitor", "21"))
        item = self.tableWidget_dispatch.item(21, 5)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(22, 0)
        item.setText(_translate("Monitor", "22"))
        item = self.tableWidget_dispatch.item(22, 1)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(22, 4)
        item.setText(_translate("Monitor", "22"))
        item = self.tableWidget_dispatch.item(22, 5)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(23, 0)
        item.setText(_translate("Monitor", "23"))
        item = self.tableWidget_dispatch.item(23, 1)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(23, 4)
        item.setText(_translate("Monitor", "23"))
        item = self.tableWidget_dispatch.item(23, 5)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(24, 0)
        item.setText(_translate("Monitor", "24"))
        item = self.tableWidget_dispatch.item(24, 1)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(24, 4)
        item.setText(_translate("Monitor", "24"))
        item = self.tableWidget_dispatch.item(24, 5)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(25, 0)
        item.setText(_translate("Monitor", "25"))
        item = self.tableWidget_dispatch.item(25, 1)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(25, 4)
        item.setText(_translate("Monitor", "25"))
        item = self.tableWidget_dispatch.item(25, 5)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(26, 0)
        item.setText(_translate("Monitor", "26"))
        item = self.tableWidget_dispatch.item(26, 1)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(26, 4)
        item.setText(_translate("Monitor", "26"))
        item = self.tableWidget_dispatch.item(26, 5)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(27, 0)
        item.setText(_translate("Monitor", "27"))
        item = self.tableWidget_dispatch.item(27, 1)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(27, 4)
        item.setText(_translate("Monitor", "27"))
        item = self.tableWidget_dispatch.item(27, 5)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(28, 0)
        item.setText(_translate("Monitor", "28"))
        item = self.tableWidget_dispatch.item(28, 1)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(28, 4)
        item.setText(_translate("Monitor", "28"))
        item = self.tableWidget_dispatch.item(28, 5)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(29, 0)
        item.setText(_translate("Monitor", "29"))
        item = self.tableWidget_dispatch.item(29, 1)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(29, 4)
        item.setText(_translate("Monitor", "29"))
        item = self.tableWidget_dispatch.item(29, 5)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(30, 0)
        item.setText(_translate("Monitor", "30"))
        item = self.tableWidget_dispatch.item(30, 1)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(30, 4)
        item.setText(_translate("Monitor", "30"))
        item = self.tableWidget_dispatch.item(30, 5)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(31, 0)
        item.setText(_translate("Monitor", "31"))
        item = self.tableWidget_dispatch.item(31, 1)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(31, 4)
        item.setText(_translate("Monitor", "31"))
        item = self.tableWidget_dispatch.item(31, 5)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(32, 4)
        item.setText(_translate("Monitor", "32"))
        item = self.tableWidget_dispatch.item(32, 5)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(33, 4)
        item.setText(_translate("Monitor", "33"))
        item = self.tableWidget_dispatch.item(33, 5)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(34, 4)
        item.setText(_translate("Monitor", "34"))
        item = self.tableWidget_dispatch.item(34, 5)
        item.setText(_translate("Monitor", "0"))
        item = self.tableWidget_dispatch.item(35, 4)
        item.setText(_translate("Monitor", "35"))
        item = self.tableWidget_dispatch.item(35, 5)
        item.setText(_translate("Monitor", "0"))
        self.tableWidget_dispatch.setSortingEnabled(__sortingEnabled)
        self.checkBox_HisPreDealMonitorData.setText(_translate("Monitor", "HisPreDealMonitorData"))
        self.label_32.setText(_translate("Monitor", "sndFldRsndCnt  "))
        self.lineEdit_sndFldRsndCnt.setText(_translate("Monitor", "0"))
        self.label_35.setText(_translate("Monitor", "repFldRsndCnt  "))
        self.lineEdit_repFldRsndCnt.setText(_translate("Monitor", "0"))
        self.label_30.setText(_translate("Monitor", "rcvCnt         "))
        self.lineEdit_recCnt.setText(_translate("Monitor", "0"))
        self.label_31.setText(_translate("Monitor", "perRcvCnt      "))
        self.lineEdit_perRcvCnt.setText(_translate("Monitor", "0"))
        self.label_33.setText(_translate("Monitor", "mtchCnt        "))
        self.lineEdit_mtcnCnt.setText(_translate("Monitor", "0"))
        self.label_36.setText(_translate("Monitor", "repTmoutRsndCnt"))
        self.lineEdit_repTmoutRsndCnt.setText(_translate("Monitor", "0"))
        self.checkBox_HisCenterMonitor.setText(_translate("Monitor", "HisCenterMonitorData"))
        self.label_40.setText(_translate("Monitor", "directInstCnt "))
        self.lineEdit_directInstCnt.setText(_translate("Monitor", "0"))
        self.label_41.setText(_translate("Monitor", "repMtchCnt    "))
        self.lineEdit_repMtchCnt.setText(_translate("Monitor", "0"))
        self.label_38.setText(_translate("Monitor", "preCnt        "))
        self.lineEdit_preCnt.setText(_translate("Monitor", "0"))
        self.label_39.setText(_translate("Monitor", "rcvMsgCnt     "))
        self.lineEdit_rcvMsgCnt.setText(_translate("Monitor", "0"))
        self.label_42.setText(_translate("Monitor", "repRtryMtchCnt"))
        self.lineEdit_repRtryMtchCnt.setText(_translate("Monitor", "0"))
        self.label_43.setText(_translate("Monitor", "repDismtchCnt "))
        self.lineEdit_repDismtchCnt.setText(_translate("Monitor", "0"))
        self.label_44.setText(_translate("Monitor", "moMsgCnt      "))
        self.lineEdit_moMsgCnt.setText(_translate("Monitor", "0"))
        self.checkBox_SHeartBeat.setText(_translate("Monitor", "SHeartBeat"))
        self.label_45.setText(_translate("Monitor", "timeInterval"))
        self.lineEdit_timeInterval.setText(_translate("Monitor", "0"))
        self.label_48.setText(_translate("Monitor", "alarm_module"))
        self.lineEdit_alarm_module.setText(_translate("Monitor", "0"))
        self.label_47.setText(_translate("Monitor", "stat        "))
        self.lineEdit_stat.setText(_translate("Monitor", "0"))
        self.checkBox_log.setText(_translate("Monitor", "log"))
        self.label_49.setText(_translate("Monitor", "level"))
        self.lineEdit_level.setText(_translate("Monitor", "0"))
        self.label_50.setText(_translate("Monitor", "ip   "))
        self.lineEdit_ip.setText(_translate("Monitor", "0"))
        self.label_52.setText(_translate("Monitor", "name "))
        self.lineEdit_name.setText(_translate("Monitor", "0"))
        self.label_53.setText(_translate("Monitor", "msg  "))
        self.lineEdit_msg.setText(_translate("Monitor", "0"))

import main_rc
