# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_SMsgHisRepData.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SMsgHisRepData(object):
    def setupUi(self, SMsgHisRepData):
        SMsgHisRepData.setObjectName("SMsgHisRepData")
        SMsgHisRepData.resize(769, 391)
        self.gridLayout = QtWidgets.QGridLayout(SMsgHisRepData)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(SMsgHisRepData)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lineEdit_mobilePhone = QtWidgets.QLineEdit(SMsgHisRepData)
        self.lineEdit_mobilePhone.setObjectName("lineEdit_mobilePhone")
        self.horizontalLayout.addWidget(self.lineEdit_mobilePhone)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(SMsgHisRepData)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.lineEdit_matchId = QtWidgets.QLineEdit(SMsgHisRepData)
        self.lineEdit_matchId.setObjectName("lineEdit_matchId")
        self.horizontalLayout_2.addWidget(self.lineEdit_matchId)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(SMsgHisRepData)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.lineEdit_resourceId = QtWidgets.QLineEdit(SMsgHisRepData)
        self.lineEdit_resourceId.setObjectName("lineEdit_resourceId")
        self.horizontalLayout_3.addWidget(self.lineEdit_resourceId)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(SMsgHisRepData)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.dateTimeEdit_reportTime = QtWidgets.QDateTimeEdit(SMsgHisRepData)
        self.dateTimeEdit_reportTime.setObjectName("dateTimeEdit_reportTime")
        self.horizontalLayout_8.addWidget(self.dateTimeEdit_reportTime)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(SMsgHisRepData)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.lineEdit_reportState = QtWidgets.QLineEdit(SMsgHisRepData)
        self.lineEdit_reportState.setObjectName("lineEdit_reportState")
        self.horizontalLayout_4.addWidget(self.lineEdit_reportState)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(SMsgHisRepData)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.dateTimeEdit_reportLocalTime = QtWidgets.QDateTimeEdit(SMsgHisRepData)
        self.dateTimeEdit_reportLocalTime.setObjectName("dateTimeEdit_reportLocalTime")
        self.horizontalLayout_9.addWidget(self.dateTimeEdit_reportLocalTime)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(SMsgHisRepData)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.lineEdit_componentFlg = QtWidgets.QLineEdit(SMsgHisRepData)
        self.lineEdit_componentFlg.setObjectName("lineEdit_componentFlg")
        self.horizontalLayout_6.addWidget(self.lineEdit_componentFlg)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(SMsgHisRepData)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.lineEdit_cycletimes = QtWidgets.QLineEdit(SMsgHisRepData)
        self.lineEdit_cycletimes.setObjectName("lineEdit_cycletimes")
        self.horizontalLayout_7.addWidget(self.lineEdit_cycletimes)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(SMsgHisRepData)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.textEdit = QtWidgets.QTextEdit(SMsgHisRepData)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_2.addWidget(self.textEdit)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 1)

        self.retranslateUi(SMsgHisRepData)
        QtCore.QMetaObject.connectSlotsByName(SMsgHisRepData)

    def retranslateUi(self, SMsgHisRepData):
        _translate = QtCore.QCoreApplication.translate
        SMsgHisRepData.setWindowTitle(_translate("SMsgHisRepData", "Form"))
        self.label.setText(_translate("SMsgHisRepData", "手机号码"))
        self.lineEdit_mobilePhone.setText(_translate("SMsgHisRepData", "13000000000"))
        self.label_2.setText(_translate("SMsgHisRepData", "匹配编号"))
        self.lineEdit_matchId.setText(_translate("SMsgHisRepData", "0"))
        self.label_3.setText(_translate("SMsgHisRepData", "资源编号"))
        self.lineEdit_resourceId.setText(_translate("SMsgHisRepData", "0"))
        self.label_8.setText(_translate("SMsgHisRepData", "消息回执时间"))
        self.dateTimeEdit_reportTime.setDisplayFormat(_translate("SMsgHisRepData", "yyyy/M/d H:mm:ss"))
        self.label_4.setText(_translate("SMsgHisRepData", "状态报告是否成功"))
        self.lineEdit_reportState.setText(_translate("SMsgHisRepData", "1"))
        self.label_9.setText(_translate("SMsgHisRepData", "状态报告本地接收时间"))
        self.dateTimeEdit_reportLocalTime.setDisplayFormat(_translate("SMsgHisRepData", "yyyy/M/d H:mm:ss"))
        self.label_6.setText(_translate("SMsgHisRepData", "Flag"))
        self.lineEdit_componentFlg.setText(_translate("SMsgHisRepData", "0"))
        self.label_7.setText(_translate("SMsgHisRepData", "循环次数"))
        self.lineEdit_cycletimes.setText(_translate("SMsgHisRepData", "0"))
        self.label_5.setText(_translate("SMsgHisRepData", "状态报告信息"))
        self.textEdit.setHtml(_translate("SMsgHisRepData", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">发送成功</p></body></html>"))

