# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_SBMSMessage.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SBMSMessage(object):
    def setupUi(self, SBMSMessage):
        SBMSMessage.setObjectName("SBMSMessage")
        SBMSMessage.resize(1004, 748)
        self.gridLayout_2 = QtWidgets.QGridLayout(SBMSMessage)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(SBMSMessage)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout = QtWidgets.QGridLayout(self.page)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter_2 = QtWidgets.QSplitter(self.page)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.layoutWidget = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.lineEdit_MsgId = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_MsgId.setObjectName("lineEdit_MsgId")
        self.horizontalLayout_2.addWidget(self.lineEdit_MsgId)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_10.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.lineEdit_Priority = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_Priority.setObjectName("lineEdit_Priority")
        self.horizontalLayout_10.addWidget(self.lineEdit_Priority)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.comboBox_MsgFormat = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_MsgFormat.sizePolicy().hasHeightForWidth())
        self.comboBox_MsgFormat.setSizePolicy(sizePolicy)
        self.comboBox_MsgFormat.setObjectName("comboBox_MsgFormat")
        self.comboBox_MsgFormat.addItem("")
        self.comboBox_MsgFormat.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_MsgFormat)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.lineEdit_PrdExId = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_PrdExId.setObjectName("lineEdit_PrdExId")
        self.horizontalLayout_4.addWidget(self.lineEdit_PrdExId)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_29 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_18.addWidget(self.label_29)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem4)
        self.lineEdit_SubmitPrdExId = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_SubmitPrdExId.setObjectName("lineEdit_SubmitPrdExId")
        self.horizontalLayout_18.addWidget(self.lineEdit_SubmitPrdExId)
        self.verticalLayout.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.dateTimeEdit_StartSendDateTime = QtWidgets.QDateTimeEdit(self.layoutWidget)
        self.dateTimeEdit_StartSendDateTime.setObjectName("dateTimeEdit_StartSendDateTime")
        self.horizontalLayout_5.addWidget(self.dateTimeEdit_StartSendDateTime)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_6.addWidget(self.label_12)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.dateTimeEdit_EndSendDateTime = QtWidgets.QDateTimeEdit(self.layoutWidget)
        self.dateTimeEdit_EndSendDateTime.setObjectName("dateTimeEdit_EndSendDateTime")
        self.horizontalLayout_6.addWidget(self.dateTimeEdit_EndSendDateTime)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_7.addWidget(self.label_11)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.timeEdit_StartSendTime = QtWidgets.QTimeEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeEdit_StartSendTime.sizePolicy().hasHeightForWidth())
        self.timeEdit_StartSendTime.setSizePolicy(sizePolicy)
        self.timeEdit_StartSendTime.setObjectName("timeEdit_StartSendTime")
        self.horizontalLayout_7.addWidget(self.timeEdit_StartSendTime)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_8.addWidget(self.label_10)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem8)
        self.timeEdit_EndSendTime = QtWidgets.QTimeEdit(self.layoutWidget)
        self.timeEdit_EndSendTime.setObjectName("timeEdit_EndSendTime")
        self.horizontalLayout_8.addWidget(self.timeEdit_EndSendTime)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem9)
        self.dateTimeEdit_CommitTime = QtWidgets.QDateTimeEdit(self.layoutWidget)
        self.dateTimeEdit_CommitTime.setObjectName("dateTimeEdit_CommitTime")
        self.horizontalLayout_9.addWidget(self.dateTimeEdit_CommitTime)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_11.addWidget(self.label_8)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem10)
        self.lineEdit_ChargeQuantity = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_ChargeQuantity.setObjectName("lineEdit_ChargeQuantity")
        self.horizontalLayout_11.addWidget(self.lineEdit_ChargeQuantity)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_12.addWidget(self.label_7)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem11)
        self.comboBox_MsgState = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_MsgState.sizePolicy().hasHeightForWidth())
        self.comboBox_MsgState.setSizePolicy(sizePolicy)
        self.comboBox_MsgState.setObjectName("comboBox_MsgState")
        self.comboBox_MsgState.addItem("")
        self.comboBox_MsgState.addItem("")
        self.comboBox_MsgState.addItem("")
        self.comboBox_MsgState.addItem("")
        self.comboBox_MsgState.addItem("")
        self.comboBox_MsgState.addItem("")
        self.horizontalLayout_12.addWidget(self.comboBox_MsgState)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_13.addWidget(self.label_13)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem12)
        self.comboBox_MsgType = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_MsgType.sizePolicy().hasHeightForWidth())
        self.comboBox_MsgType.setSizePolicy(sizePolicy)
        self.comboBox_MsgType.setObjectName("comboBox_MsgType")
        self.comboBox_MsgType.addItem("")
        self.comboBox_MsgType.addItem("")
        self.horizontalLayout_13.addWidget(self.comboBox_MsgType)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_14.addWidget(self.label_14)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem13)
        self.lineEdit_MobilesCount = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_MobilesCount.setObjectName("lineEdit_MobilesCount")
        self.horizontalLayout_14.addWidget(self.lineEdit_MobilesCount)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_15 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_15.addWidget(self.label_15)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem14)
        self.comboBox_SubmitType = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_SubmitType.sizePolicy().hasHeightForWidth())
        self.comboBox_SubmitType.setSizePolicy(sizePolicy)
        self.comboBox_SubmitType.setObjectName("comboBox_SubmitType")
        self.comboBox_SubmitType.addItem("")
        self.comboBox_SubmitType.addItem("")
        self.horizontalLayout_15.addWidget(self.comboBox_SubmitType)
        self.verticalLayout.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_16 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_16.addWidget(self.label_16)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem15)
        self.lineEdit_AccId = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_AccId.setObjectName("lineEdit_AccId")
        self.horizontalLayout_16.addWidget(self.lineEdit_AccId)
        self.verticalLayout.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_30 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_19.addWidget(self.label_30)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem16)
        self.lineEdit_AuditorId = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_AuditorId.setObjectName("lineEdit_AuditorId")
        self.horizontalLayout_19.addWidget(self.lineEdit_AuditorId)
        self.verticalLayout.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_17 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_17.addWidget(self.label_17)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem17)
        self.lineEdit_CommitIp = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_CommitIp.setObjectName("lineEdit_CommitIp")
        self.horizontalLayout_17.addWidget(self.lineEdit_CommitIp)
        self.verticalLayout.addLayout(self.horizontalLayout_17)
        self.layoutWidget_2 = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.line = QtWidgets.QFrame(self.layoutWidget_2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.label_57 = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_57.sizePolicy().hasHeightForWidth())
        self.label_57.setSizePolicy(sizePolicy)
        self.label_57.setObjectName("label_57")
        self.horizontalLayout_46.addWidget(self.label_57)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_46.addItem(spacerItem18)
        self.lineEdit_mobile = QtWidgets.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_mobile.sizePolicy().hasHeightForWidth())
        self.lineEdit_mobile.setSizePolicy(sizePolicy)
        self.lineEdit_mobile.setObjectName("lineEdit_mobile")
        self.horizontalLayout_46.addWidget(self.lineEdit_mobile)
        self.verticalLayout_4.addLayout(self.horizontalLayout_46)
        self.horizontalLayout_47 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_47.setObjectName("horizontalLayout_47")
        self.label_58 = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_58.sizePolicy().hasHeightForWidth())
        self.label_58.setSizePolicy(sizePolicy)
        self.label_58.setObjectName("label_58")
        self.horizontalLayout_47.addWidget(self.label_58)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_47.addItem(spacerItem19)
        self.lineEdit_sign = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_sign.setObjectName("lineEdit_sign")
        self.horizontalLayout_47.addWidget(self.lineEdit_sign)
        self.verticalLayout_4.addLayout(self.horizontalLayout_47)
        self.horizontalLayout_48 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_48.setObjectName("horizontalLayout_48")
        self.label_59 = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_59.sizePolicy().hasHeightForWidth())
        self.label_59.setSizePolicy(sizePolicy)
        self.label_59.setObjectName("label_59")
        self.horizontalLayout_48.addWidget(self.label_59)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_48.addItem(spacerItem20)
        self.lineEdit_extnum = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_extnum.setObjectName("lineEdit_extnum")
        self.horizontalLayout_48.addWidget(self.lineEdit_extnum)
        self.verticalLayout_4.addLayout(self.horizontalLayout_48)
        self.horizontalLayout_49 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_49.setObjectName("horizontalLayout_49")
        self.label_60 = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_60.sizePolicy().hasHeightForWidth())
        self.label_60.setSizePolicy(sizePolicy)
        self.label_60.setObjectName("label_60")
        self.horizontalLayout_49.addWidget(self.label_60)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_49.addItem(spacerItem21)
        self.lineEdit_accmsgid = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_accmsgid.setObjectName("lineEdit_accmsgid")
        self.horizontalLayout_49.addWidget(self.lineEdit_accmsgid)
        self.verticalLayout_4.addLayout(self.horizontalLayout_49)
        self.horizontalLayout_50 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_50.setObjectName("horizontalLayout_50")
        self.label_61 = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_61.sizePolicy().hasHeightForWidth())
        self.label_61.setSizePolicy(sizePolicy)
        self.label_61.setObjectName("label_61")
        self.horizontalLayout_50.addWidget(self.label_61)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_50.addItem(spacerItem22)
        self.lineEdit_title = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_title.setObjectName("lineEdit_title")
        self.horizontalLayout_50.addWidget(self.lineEdit_title)
        self.verticalLayout_4.addLayout(self.horizontalLayout_50)
        self.horizontalLayout_51 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_51.setObjectName("horizontalLayout_51")
        self.label_62 = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_62.sizePolicy().hasHeightForWidth())
        self.label_62.setSizePolicy(sizePolicy)
        self.label_62.setObjectName("label_62")
        self.horizontalLayout_51.addWidget(self.label_62)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_51.addItem(spacerItem23)
        self.lineEdit_filepath = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_filepath.setObjectName("lineEdit_filepath")
        self.horizontalLayout_51.addWidget(self.lineEdit_filepath)
        self.verticalLayout_4.addLayout(self.horizontalLayout_51)
        self.gridLayout.addWidget(self.splitter_2, 0, 0, 1, 1)
        self.splitter = QtWidgets.QSplitter(self.page)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.layoutWidget_3 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.label_18 = QtWidgets.QLabel(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_34.addWidget(self.label_18)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem24)
        self.lineEdit_InnerDispatchTimes = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_InnerDispatchTimes.setObjectName("lineEdit_InnerDispatchTimes")
        self.horizontalLayout_34.addWidget(self.lineEdit_InnerDispatchTimes)
        self.verticalLayout_3.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.label_19 = QtWidgets.QLabel(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_35.addWidget(self.label_19)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem25)
        self.lineEdit_Pagetotal = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_Pagetotal.setObjectName("lineEdit_Pagetotal")
        self.horizontalLayout_35.addWidget(self.lineEdit_Pagetotal)
        self.verticalLayout_3.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.label_20 = QtWidgets.QLabel(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_36.addWidget(self.label_20)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_36.addItem(spacerItem26)
        self.lineEdit_FlagBits = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_FlagBits.setObjectName("lineEdit_FlagBits")
        self.horizontalLayout_36.addWidget(self.lineEdit_FlagBits)
        self.verticalLayout_3.addLayout(self.horizontalLayout_36)
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.label_21 = QtWidgets.QLabel(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_37.addWidget(self.label_21)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_37.addItem(spacerItem27)
        self.lineEdit_LastFailResId = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_LastFailResId.setObjectName("lineEdit_LastFailResId")
        self.horizontalLayout_37.addWidget(self.lineEdit_LastFailResId)
        self.verticalLayout_3.addLayout(self.horizontalLayout_37)
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.label_22 = QtWidgets.QLabel(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_38.addWidget(self.label_22)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_38.addItem(spacerItem28)
        self.comboBox_FailedType = QtWidgets.QComboBox(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_FailedType.sizePolicy().hasHeightForWidth())
        self.comboBox_FailedType.setSizePolicy(sizePolicy)
        self.comboBox_FailedType.setObjectName("comboBox_FailedType")
        self.comboBox_FailedType.addItem("")
        self.comboBox_FailedType.addItem("")
        self.comboBox_FailedType.addItem("")
        self.comboBox_FailedType.addItem("")
        self.comboBox_FailedType.addItem("")
        self.comboBox_FailedType.addItem("")
        self.comboBox_FailedType.addItem("")
        self.comboBox_FailedType.addItem("")
        self.comboBox_FailedType.addItem("")
        self.horizontalLayout_38.addWidget(self.comboBox_FailedType)
        self.verticalLayout_3.addLayout(self.horizontalLayout_38)
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.label_23 = QtWidgets.QLabel(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_39.addWidget(self.label_23)
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_39.addItem(spacerItem29)
        self.lineEdit_FailedState = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_FailedState.setObjectName("lineEdit_FailedState")
        self.horizontalLayout_39.addWidget(self.lineEdit_FailedState)
        self.verticalLayout_3.addLayout(self.horizontalLayout_39)
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.label_25 = QtWidgets.QLabel(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_41.addWidget(self.label_25)
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_41.addItem(spacerItem30)
        self.lineEdit_ResSendTimes = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_ResSendTimes.setObjectName("lineEdit_ResSendTimes")
        self.horizontalLayout_41.addWidget(self.lineEdit_ResSendTimes)
        self.verticalLayout_3.addLayout(self.horizontalLayout_41)
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.label_24 = QtWidgets.QLabel(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_40.addWidget(self.label_24)
        spacerItem31 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_40.addItem(spacerItem31)
        self.dateTimeEdit_LastDiapatchTime = QtWidgets.QDateTimeEdit(self.layoutWidget_3)
        self.dateTimeEdit_LastDiapatchTime.setObjectName("dateTimeEdit_LastDiapatchTime")
        self.horizontalLayout_40.addWidget(self.dateTimeEdit_LastDiapatchTime)
        self.verticalLayout_3.addLayout(self.horizontalLayout_40)
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.label_26 = QtWidgets.QLabel(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_42.addWidget(self.label_26)
        spacerItem32 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_42.addItem(spacerItem32)
        self.lineEdit_TotalSndFldResndTimes = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_TotalSndFldResndTimes.setObjectName("lineEdit_TotalSndFldResndTimes")
        self.horizontalLayout_42.addWidget(self.lineEdit_TotalSndFldResndTimes)
        self.verticalLayout_3.addLayout(self.horizontalLayout_42)
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.label_27 = QtWidgets.QLabel(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_43.addWidget(self.label_27)
        spacerItem33 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_43.addItem(spacerItem33)
        self.lineEdit_TotalRepFldResndTimes = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_TotalRepFldResndTimes.setObjectName("lineEdit_TotalRepFldResndTimes")
        self.horizontalLayout_43.addWidget(self.lineEdit_TotalRepFldResndTimes)
        self.verticalLayout_3.addLayout(self.horizontalLayout_43)
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.label_28 = QtWidgets.QLabel(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_28.sizePolicy().hasHeightForWidth())
        self.label_28.setSizePolicy(sizePolicy)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_44.addWidget(self.label_28)
        spacerItem34 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_44.addItem(spacerItem34)
        self.lineEdit_PackageTotal = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_PackageTotal.setObjectName("lineEdit_PackageTotal")
        self.horizontalLayout_44.addWidget(self.lineEdit_PackageTotal)
        self.verticalLayout_3.addLayout(self.horizontalLayout_44)
        self.horizontalLayout_45 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.label_56 = QtWidgets.QLabel(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_56.sizePolicy().hasHeightForWidth())
        self.label_56.setSizePolicy(sizePolicy)
        self.label_56.setObjectName("label_56")
        self.horizontalLayout_45.addWidget(self.label_56)
        spacerItem35 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_45.addItem(spacerItem35)
        self.lineEdit_PackageNum = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_PackageNum.setObjectName("lineEdit_PackageNum")
        self.horizontalLayout_45.addWidget(self.lineEdit_PackageNum)
        self.verticalLayout_3.addLayout(self.horizontalLayout_45)
        self.layoutWidget_4 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.line_3 = QtWidgets.QFrame(self.layoutWidget_4)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_5.addWidget(self.line_3)
        self.label_63 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_63.setFont(font)
        self.label_63.setObjectName("label_63")
        self.verticalLayout_5.addWidget(self.label_63)
        self.textEdit_content = QtWidgets.QTextEdit(self.layoutWidget_4)
        self.textEdit_content.setObjectName("textEdit_content")
        self.verticalLayout_5.addWidget(self.textEdit_content)
        self.gridLayout.addWidget(self.splitter, 0, 2, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.page)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 0, 1, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout_2.addWidget(self.stackedWidget, 0, 0, 1, 1)

        self.retranslateUi(SBMSMessage)
        self.stackedWidget.setCurrentIndex(0)
        self.comboBox_SubmitType.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(SBMSMessage)

    def retranslateUi(self, SBMSMessage):
        _translate = QtCore.QCoreApplication.translate
        SBMSMessage.setWindowTitle(_translate("SBMSMessage", "Form"))
        self.label_4.setText(_translate("SBMSMessage", "消息ID"))
        self.lineEdit_MsgId.setText(_translate("SBMSMessage", "0"))
        self.label_2.setText(_translate("SBMSMessage", "消息级别"))
        self.lineEdit_Priority.setText(_translate("SBMSMessage", "0"))
        self.label_3.setText(_translate("SBMSMessage", "消息编码方式"))
        self.comboBox_MsgFormat.setItemText(0, _translate("SBMSMessage", "ASCII"))
        self.comboBox_MsgFormat.setItemText(1, _translate("SBMSMessage", "WCHA"))
        self.label_5.setText(_translate("SBMSMessage", "扩展产品Id"))
        self.lineEdit_PrdExId.setText(_translate("SBMSMessage", "0"))
        self.label_29.setText(_translate("SBMSMessage", "提交的扩展产品Id"))
        self.lineEdit_SubmitPrdExId.setText(_translate("SBMSMessage", "0"))
        self.label_6.setText(_translate("SBMSMessage", "开始发送日期"))
        self.dateTimeEdit_StartSendDateTime.setDisplayFormat(_translate("SBMSMessage", "yyyy/M/d H:mm:ss"))
        self.label_12.setText(_translate("SBMSMessage", "结束发送日期"))
        self.dateTimeEdit_EndSendDateTime.setDisplayFormat(_translate("SBMSMessage", "yyyy/M/d H:mm:ss"))
        self.label_11.setText(_translate("SBMSMessage", "开始发送时段"))
        self.timeEdit_StartSendTime.setDisplayFormat(_translate("SBMSMessage", "H:mm::ss"))
        self.label_10.setText(_translate("SBMSMessage", "结束发送时段"))
        self.timeEdit_EndSendTime.setDisplayFormat(_translate("SBMSMessage", "H:mm::ss"))
        self.label_9.setText(_translate("SBMSMessage", "信息提交时间"))
        self.dateTimeEdit_CommitTime.setDisplayFormat(_translate("SBMSMessage", "yyyy/M/d H:mm:ss"))
        self.label_8.setText(_translate("SBMSMessage", "计费号码数"))
        self.lineEdit_ChargeQuantity.setText(_translate("SBMSMessage", "0"))
        self.label_7.setText(_translate("SBMSMessage", "消息状态"))
        self.comboBox_MsgState.setItemText(0, _translate("SBMSMessage", "待审核"))
        self.comboBox_MsgState.setItemText(1, _translate("SBMSMessage", "已审核"))
        self.comboBox_MsgState.setItemText(2, _translate("SBMSMessage", "已驳回"))
        self.comboBox_MsgState.setItemText(3, _translate("SBMSMessage", "已发送"))
        self.comboBox_MsgState.setItemText(4, _translate("SBMSMessage", "全部取消"))
        self.comboBox_MsgState.setItemText(5, _translate("SBMSMessage", "二审"))
        self.label_13.setText(_translate("SBMSMessage", "信息类型"))
        self.comboBox_MsgType.setItemText(0, _translate("SBMSMessage", "短信"))
        self.comboBox_MsgType.setItemText(1, _translate("SBMSMessage", "彩信"))
        self.label_14.setText(_translate("SBMSMessage", "号码个数"))
        self.lineEdit_MobilesCount.setText(_translate("SBMSMessage", "0"))
        self.label_15.setText(_translate("SBMSMessage", "提交类型"))
        self.comboBox_SubmitType.setItemText(0, _translate("SBMSMessage", "其他接口"))
        self.comboBox_SubmitType.setItemText(1, _translate("SBMSMessage", "提交接口"))
        self.label_16.setText(_translate("SBMSMessage", "账户Id"))
        self.lineEdit_AccId.setText(_translate("SBMSMessage", "0"))
        self.label_30.setText(_translate("SBMSMessage", "审核Id"))
        self.lineEdit_AuditorId.setText(_translate("SBMSMessage", "0"))
        self.label_17.setText(_translate("SBMSMessage", "提交IP"))
        self.lineEdit_CommitIp.setText(_translate("SBMSMessage", "127.0.0.1"))
        self.label_57.setText(_translate("SBMSMessage", "号码"))
        self.lineEdit_mobile.setText(_translate("SBMSMessage", "13000000000"))
        self.label_58.setText(_translate("SBMSMessage", "签名"))
        self.lineEdit_sign.setText(_translate("SBMSMessage", "【微网通联】"))
        self.label_59.setText(_translate("SBMSMessage", "扩展号码"))
        self.lineEdit_extnum.setText(_translate("SBMSMessage", "1069"))
        self.label_60.setText(_translate("SBMSMessage", "客户自定义参数"))
        self.lineEdit_accmsgid.setText(_translate("SBMSMessage", "0"))
        self.label_61.setText(_translate("SBMSMessage", "彩信标题"))
        self.lineEdit_title.setText(_translate("SBMSMessage", "测试"))
        self.label_62.setText(_translate("SBMSMessage", "彩信存储文件路径"))
        self.lineEdit_filepath.setText(_translate("SBMSMessage", "C:/"))
        self.label_18.setText(_translate("SBMSMessage", "进入调度中心次数"))
        self.lineEdit_InnerDispatchTimes.setText(_translate("SBMSMessage", "0"))
        self.label_19.setText(_translate("SBMSMessage", "长短信页数"))
        self.lineEdit_Pagetotal.setText(_translate("SBMSMessage", "0"))
        self.label_20.setText(_translate("SBMSMessage", "FlagBits"))
        self.lineEdit_FlagBits.setText(_translate("SBMSMessage", "0"))
        self.label_21.setText(_translate("SBMSMessage", "最后一次资源发送失败id"))
        self.lineEdit_LastFailResId.setText(_translate("SBMSMessage", "0"))
        self.label_22.setText(_translate("SBMSMessage", "信息失败类型"))
        self.comboBox_FailedType.setItemText(0, _translate("SBMSMessage", "成功"))
        self.comboBox_FailedType.setItemText(1, _translate("SBMSMessage", "调度失败"))
        self.comboBox_FailedType.setItemText(2, _translate("SBMSMessage", "发送失败"))
        self.comboBox_FailedType.setItemText(3, _translate("SBMSMessage", "状态报告失败"))
        self.comboBox_FailedType.setItemText(4, _translate("SBMSMessage", "黑名单"))
        self.comboBox_FailedType.setItemText(5, _translate("SBMSMessage", "无效号码"))
        self.comboBox_FailedType.setItemText(6, _translate("SBMSMessage", "人工取消"))
        self.comboBox_FailedType.setItemText(7, _translate("SBMSMessage", "信息失效"))
        self.comboBox_FailedType.setItemText(8, _translate("SBMSMessage", "提交限量"))
        self.label_23.setText(_translate("SBMSMessage", "失败状态值"))
        self.lineEdit_FailedState.setText(_translate("SBMSMessage", "0"))
        self.label_25.setText(_translate("SBMSMessage", "资源发送次数"))
        self.lineEdit_ResSendTimes.setText(_translate("SBMSMessage", "0"))
        self.label_24.setText(_translate("SBMSMessage", "最后一次调度时间"))
        self.dateTimeEdit_LastDiapatchTime.setDisplayFormat(_translate("SBMSMessage", "yyyy/M/d H:mm:ss"))
        self.label_26.setText(_translate("SBMSMessage", "发送失败总重发次数"))
        self.lineEdit_TotalSndFldResndTimes.setText(_translate("SBMSMessage", "0"))
        self.label_27.setText(_translate("SBMSMessage", "回执失败/超时总重发次数"))
        self.lineEdit_TotalRepFldResndTimes.setText(_translate("SBMSMessage", "0"))
        self.label_28.setText(_translate("SBMSMessage", "分包号码的总包数"))
        self.lineEdit_PackageTotal.setText(_translate("SBMSMessage", "0"))
        self.label_56.setText(_translate("SBMSMessage", "分包号码的当前包号"))
        self.lineEdit_PackageNum.setText(_translate("SBMSMessage", "0"))
        self.label_63.setText(_translate("SBMSMessage", "短信内容"))

