# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_SHisMOData.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SHisMOData(object):
    def setupUi(self, SHisMOData):
        SHisMOData.setObjectName("SHisMOData")
        SHisMOData.resize(965, 525)
        self.gridLayout = QtWidgets.QGridLayout(SHisMOData)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(SHisMOData)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lineEdit_msgId = QtWidgets.QLineEdit(SHisMOData)
        self.lineEdit_msgId.setObjectName("lineEdit_msgId")
        self.horizontalLayout.addWidget(self.lineEdit_msgId)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(SHisMOData)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.lineEdit_msgType = QtWidgets.QLineEdit(SHisMOData)
        self.lineEdit_msgType.setObjectName("lineEdit_msgType")
        self.horizontalLayout_2.addWidget(self.lineEdit_msgType)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(SHisMOData)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.lineEdit_accId = QtWidgets.QLineEdit(SHisMOData)
        self.lineEdit_accId.setObjectName("lineEdit_accId")
        self.horizontalLayout_3.addWidget(self.lineEdit_accId)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(SHisMOData)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.lineEdit_mobile = QtWidgets.QLineEdit(SHisMOData)
        self.lineEdit_mobile.setObjectName("lineEdit_mobile")
        self.horizontalLayout_4.addWidget(self.lineEdit_mobile)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(SHisMOData)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(SHisMOData)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.horizontalLayout_5.addWidget(self.dateTimeEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(SHisMOData)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.lineEdit_resId = QtWidgets.QLineEdit(SHisMOData)
        self.lineEdit_resId.setObjectName("lineEdit_resId")
        self.horizontalLayout_6.addWidget(self.lineEdit_resId)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(SHisMOData)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.lineEdit_dealTimes = QtWidgets.QLineEdit(SHisMOData)
        self.lineEdit_dealTimes.setObjectName("lineEdit_dealTimes")
        self.horizontalLayout_7.addWidget(self.lineEdit_dealTimes)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(SHisMOData)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem7)
        self.lineEdit_SpNum = QtWidgets.QLineEdit(SHisMOData)
        self.lineEdit_SpNum.setObjectName("lineEdit_SpNum")
        self.horizontalLayout_8.addWidget(self.lineEdit_SpNum)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_9 = QtWidgets.QLabel(SHisMOData)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.textEdit = QtWidgets.QTextEdit(SHisMOData)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 1, 1)

        self.retranslateUi(SHisMOData)
        QtCore.QMetaObject.connectSlotsByName(SHisMOData)

    def retranslateUi(self, SHisMOData):
        _translate = QtCore.QCoreApplication.translate
        SHisMOData.setWindowTitle(_translate("SHisMOData", "Form"))
        self.label.setText(_translate("SHisMOData", "消息ID  "))
        self.lineEdit_msgId.setText(_translate("SHisMOData", "0"))
        self.label_2.setText(_translate("SHisMOData", "消息类型"))
        self.lineEdit_msgType.setText(_translate("SHisMOData", "0"))
        self.label_3.setText(_translate("SHisMOData", "用户ID  "))
        self.lineEdit_accId.setText(_translate("SHisMOData", "123"))
        self.label_4.setText(_translate("SHisMOData", "手机号码"))
        self.lineEdit_mobile.setText(_translate("SHisMOData", "13000000000"))
        self.label_5.setText(_translate("SHisMOData", "上行时间"))
        self.label_6.setText(_translate("SHisMOData", "资源ID  "))
        self.lineEdit_resId.setText(_translate("SHisMOData", "0"))
        self.label_7.setText(_translate("SHisMOData", "处理次数"))
        self.lineEdit_dealTimes.setText(_translate("SHisMOData", "0"))
        self.label_8.setText(_translate("SHisMOData", "服务商号"))
        self.lineEdit_SpNum.setText(_translate("SHisMOData", "1069"))
        self.label_9.setText(_translate("SHisMOData", "上行内容"))
        self.textEdit.setHtml(_translate("SHisMOData", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">你好</p></body></html>"))

