# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Search.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FindMessage(object):
    def setupUi(self, FindMessage):
        FindMessage.setObjectName("FindMessage")
        FindMessage.setWindowModality(QtCore.Qt.NonModal)
        FindMessage.resize(448, 309)
        self.gridLayout = QtWidgets.QGridLayout(FindMessage)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(FindMessage)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(FindMessage)
        self.comboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(FindMessage)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.groupBox)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.checkBox_time = QtWidgets.QCheckBox(self.page)
        self.checkBox_time.setObjectName("checkBox_time")
        self.horizontalLayout_4.addWidget(self.checkBox_time)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.dateTimeEdit_start = QtWidgets.QDateTimeEdit(self.page)
        self.dateTimeEdit_start.setObjectName("dateTimeEdit_start")
        self.horizontalLayout_2.addWidget(self.dateTimeEdit_start)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.page)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.dateTimeEdit_end = QtWidgets.QDateTimeEdit(self.page)
        self.dateTimeEdit_end.setObjectName("dateTimeEdit_end")
        self.horizontalLayout_3.addWidget(self.dateTimeEdit_end)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.checkBox_id = QtWidgets.QCheckBox(self.page)
        self.checkBox_id.setObjectName("checkBox_id")
        self.horizontalLayout_7.addWidget(self.checkBox_id)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.page)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.lineEdit_max = QtWidgets.QLineEdit(self.page)
        self.lineEdit_max.setMinimumSize(QtCore.QSize(158, 0))
        self.lineEdit_max.setObjectName("lineEdit_max")
        self.horizontalLayout_5.addWidget(self.lineEdit_max)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.page)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.lineEdit_min = QtWidgets.QLineEdit(self.page)
        self.lineEdit_min.setObjectName("lineEdit_min")
        self.horizontalLayout_6.addWidget(self.lineEdit_min)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7.addLayout(self.verticalLayout_2)
        self.gridLayout_3.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout_2.addWidget(self.stackedWidget, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(FindMessage)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 1)

        self.retranslateUi(FindMessage)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(FindMessage)

    def retranslateUi(self, FindMessage):
        _translate = QtCore.QCoreApplication.translate
        FindMessage.setWindowTitle(_translate("FindMessage", "查找消息"))
        self.label.setText(_translate("FindMessage", "要筛选的消息结构"))
        self.comboBox.setItemText(0, _translate("FindMessage", "SBmsMessage"))
        self.comboBox.setItemText(1, _translate("FindMessage", "SMsgSendData"))
        self.groupBox.setTitle(_translate("FindMessage", "筛选条件"))
        self.checkBox_time.setText(_translate("FindMessage", "生产时间"))
        self.label_2.setText(_translate("FindMessage", "开始时间"))
        self.label_3.setText(_translate("FindMessage", "结束时间"))
        self.checkBox_id.setText(_translate("FindMessage", "MsgID            "))
        self.label_5.setText(_translate("FindMessage", "最大值  "))
        self.lineEdit_max.setText(_translate("FindMessage", "0"))
        self.label_6.setText(_translate("FindMessage", "最小值  "))
        self.lineEdit_min.setText(_translate("FindMessage", "0"))

